// GENERATED by the WO-4 architecture grammar port, restructured to the
// three-tier model by WO-4.1 (see grammar-port-manifest.json and the
// amendment memo). Classic content is migration-source DATA; classic code
// is never imported. Edit through the operator pathway, not by hand.
import type { ArchitectureGrammarPackInput } from "../schema.js";

export const grammarArchetypeDomainLibrary: ArchitectureGrammarPackInput = {
  "id": "grammar-archetype-domain-library",
  "version": "1.0.0",
  "kind": "overlay",
  "tier": "archetype",
  "description": "Architecture archetype: Domain-first library with no route/service requirement. Ported from classic's topology template \"domain_library\"; carries the layered-school grammar scoped to its layers. Backs findings only when ratified in repo config.",
  "provenance": {
    "migratedFrom": "legacy-source topology-contract-inference.ts BUILTIN_TOPOLOGY_TEMPLATES.domain_library",
    "note": "re-shelved school content per the WO-4.1 amendment memo"
  },
  "topology": {
    "archetype": "domain_library",
    "description": "Domain-first library with no route/service requirement.",
    "requiredLayers": [
      "domain"
    ],
    "layerEdges": [
      {
        "fromLayer": "domain",
        "toLayer": "infra",
        "required": false,
        "forbidden": true
      }
    ],
    "source": "topology-contract-inference.ts#domain_library"
  },
  "layers": [
    {
      "id": "domain",
      "name": "Domain",
      "description": "Business logic layer. Pure calculations, validations, transformations.\nDomain functions should be pure (no side effects) and deterministic.\nThis is where the actual \"thinking\" happens.\n",
      "position": 2,
      "paths": [
        "**/domain/**",
        "**/logic/**"
      ],
      "allowedTypes": [
        "Engine",
        "Resolver",
        "Evaluator",
        "Factory",
        "Builder",
        "Validator",
        "Transformer",
        "Calculator",
        "Adapter",
        "Types",
        "Schema"
      ],
      "responsibilities": [
        "Pure business calculations",
        "Domain validation logic",
        "Data transformations (derive, map, filter)",
        "Type definitions and Zod schemas",
        "State derivation (deriveAll, deriveProgress, etc.)",
        "Decision preparation for DDE"
      ],
      "forbidden": [],
      "canImport": [],
      "cannotImport": [],
      "allowedVerbCategories": [
        "transformation",
        "validation",
        "construction",
        "extraction"
      ],
      "source": "layers.ontology.yaml#layers.domain"
    },
    {
      "id": "config",
      "name": "Configuration",
      "description": "Static configuration. Constants, defaults, manifests. No runtime logic.\nConfig files provide values that can be imported by any layer.\n",
      "position": 4,
      "paths": [
        "**/config/**",
        "**/*.config.*",
        "**/*.manifest.*"
      ],
      "allowedTypes": [
        "Config",
        "Manifest",
        "Constants",
        "Defaults",
        "Types",
        "Schema"
      ],
      "responsibilities": [
        "Define constants",
        "Define default values",
        "Define manifests",
        "Define static configuration",
        "Gate definitions (YAML)"
      ],
      "forbidden": [],
      "canImport": [],
      "cannotImport": [],
      "allowedVerbCategories": [
        "registration"
      ],
      "source": "layers.ontology.yaml#layers.config"
    }
  ],
  "verbCategories": [
    {
      "id": "coordination",
      "name": "Coordination",
      "description": "Operations that coordinate or orchestrate other components. These verbs\nsignal hub behavior - files that coordinate should have high fan-in.\nOrchestration means coordination WITHOUT decision-making; DDE decides\nWHAT, orchestration executes HOW.\n",
      "canonicalVerbs": [
        "orchestrate",
        "coordinate",
        "route",
        "schedule"
      ],
      "allowedInLayers": [],
      "forbiddenInLayers": [
        "domain",
        "config"
      ],
      "structuralImplications": {
        "hubIndicator": true,
        "purityViolation": true,
        "fanInExpectation": "high"
      },
      "vocabularyCategory": "system",
      "source": "verb-categories.ontology.yaml#categories.coordination"
    },
    {
      "id": "delegation",
      "name": "Delegation",
      "description": "Lightweight 1:1 handoff to another component. Delegation is not\norchestration: the delegating file does not coordinate multiple actors\nor own complex sequencing.\n",
      "canonicalVerbs": [
        "delegate",
        "dispatch"
      ],
      "allowedInLayers": [],
      "forbiddenInLayers": [
        "domain",
        "config"
      ],
      "structuralImplications": {
        "hubIndicator": false,
        "purityViolation": false,
        "fanInExpectation": "medium"
      },
      "vocabularyCategory": "system",
      "source": "verb-categories.ontology.yaml#categories.delegation"
    },
    {
      "id": "transformation",
      "name": "Transformation",
      "description": "Pure data transformations without side effects. These verbs are the\nhallmark of domain layer code - deterministic, testable, no I/O.\nBusiness logic lives here.\n",
      "canonicalVerbs": [
        "transform",
        "derive",
        "calculate",
        "compute",
        "map",
        "filter",
        "merge",
        "format",
        "aggregate",
        "reduce"
      ],
      "allowedInLayers": [
        "domain"
      ],
      "forbiddenInLayers": [],
      "structuralImplications": {
        "hubIndicator": false,
        "purityViolation": false,
        "fanInExpectation": "varies"
      },
      "vocabularyCategory": "transform",
      "source": "verb-categories.ontology.yaml#categories.transformation"
    },
    {
      "id": "state_mutation",
      "name": "State Mutation",
      "description": "Operations that change persisted state (database, cache, storage).\nThese verbs signal I/O and side effects - must be in infra layer.\n",
      "canonicalVerbs": [
        "persist",
        "save",
        "update",
        "delete",
        "cache",
        "clear",
        "write",
        "insert",
        "upsert"
      ],
      "allowedInLayers": [],
      "forbiddenInLayers": [
        "domain",
        "config"
      ],
      "structuralImplications": {
        "hubIndicator": false,
        "purityViolation": true,
        "fanInExpectation": "varies"
      },
      "vocabularyCategory": "write",
      "source": "verb-categories.ontology.yaml#categories.state_mutation"
    },
    {
      "id": "data_access",
      "name": "Data Access",
      "description": "Operations that read data from external sources without side effects.\nReading is still I/O and belongs in infra layer.\n",
      "canonicalVerbs": [
        "fetch",
        "load",
        "get",
        "find",
        "query",
        "read",
        "list",
        "select"
      ],
      "allowedInLayers": [],
      "forbiddenInLayers": [
        "domain"
      ],
      "structuralImplications": {
        "hubIndicator": false,
        "purityViolation": true,
        "fanInExpectation": "varies"
      },
      "vocabularyCategory": "read",
      "source": "verb-categories.ontology.yaml#categories.data_access"
    },
    {
      "id": "validation",
      "name": "Validation",
      "description": "Data validation, classification, and verification. Primary use at\nboundaries (routes) with Zod schemas. Domain validation for\nbusiness rules.\n",
      "canonicalVerbs": [
        "validate",
        "classify",
        "evaluate",
        "parse",
        "check",
        "verify",
        "assert",
        "sanitize"
      ],
      "allowedInLayers": [
        "domain"
      ],
      "forbiddenInLayers": [],
      "structuralImplications": {
        "hubIndicator": false,
        "purityViolation": false,
        "fanInExpectation": "varies"
      },
      "vocabularyCategory": "validate",
      "source": "verb-categories.ontology.yaml#categories.validation"
    },
    {
      "id": "lifecycle",
      "name": "Lifecycle",
      "description": "Component lifecycle management (creation, initialization, destruction).\nUsed in services for operation lifecycle and UI for React lifecycle.\n",
      "canonicalVerbs": [
        "create",
        "initialize",
        "setup",
        "destroy",
        "dispose",
        "mount",
        "unmount",
        "reset"
      ],
      "allowedInLayers": [],
      "forbiddenInLayers": [
        "config"
      ],
      "structuralImplications": {
        "hubIndicator": false,
        "purityViolation": "varies",
        "fanInExpectation": "low"
      },
      "vocabularyCategory": "system",
      "source": "verb-categories.ontology.yaml#categories.lifecycle"
    },
    {
      "id": "io_streaming",
      "name": "I/O Streaming",
      "description": "I/O operations and streaming/pub-sub patterns. SSE, WebSocket,\nevent emitters. Used in infra for external I/O, UI for subscriptions.\n",
      "canonicalVerbs": [
        "stream",
        "subscribe",
        "publish",
        "emit",
        "listen",
        "export",
        "broadcast",
        "pipe"
      ],
      "allowedInLayers": [],
      "forbiddenInLayers": [
        "domain"
      ],
      "structuralImplications": {
        "hubIndicator": false,
        "purityViolation": true,
        "fanInExpectation": "varies"
      },
      "vocabularyCategory": "communicate",
      "source": "verb-categories.ontology.yaml#categories.io_streaming"
    },
    {
      "id": "construction",
      "name": "Construction",
      "description": "Building complex objects, rendering output, or encoding data.\nUsed in domain for factories, UI for rendering.\n",
      "canonicalVerbs": [
        "build",
        "generate",
        "render",
        "serialize",
        "encode",
        "compose",
        "assemble",
        "create"
      ],
      "allowedInLayers": [
        "domain"
      ],
      "forbiddenInLayers": [],
      "structuralImplications": {
        "hubIndicator": false,
        "purityViolation": false,
        "fanInExpectation": "varies"
      },
      "vocabularyCategory": "create",
      "source": "verb-categories.ontology.yaml#categories.construction"
    },
    {
      "id": "extraction",
      "name": "Extraction",
      "description": "Extracting structured data from unstructured sources.\nParsing, deserialization, decoding.\n",
      "canonicalVerbs": [
        "extract",
        "deserialize",
        "decode",
        "decompress",
        "unwrap",
        "parse"
      ],
      "allowedInLayers": [
        "domain"
      ],
      "forbiddenInLayers": [],
      "structuralImplications": {
        "hubIndicator": false,
        "purityViolation": false,
        "fanInExpectation": "low"
      },
      "vocabularyCategory": "transform",
      "source": "verb-categories.ontology.yaml#categories.extraction"
    },
    {
      "id": "registration",
      "name": "Registration",
      "description": "Registry and discovery operations. DI containers, service locators,\nmodule registration.\n",
      "canonicalVerbs": [
        "register",
        "resolve",
        "discover",
        "inject",
        "provide",
        "define"
      ],
      "allowedInLayers": [
        "config"
      ],
      "forbiddenInLayers": [],
      "structuralImplications": {
        "hubIndicator": true,
        "purityViolation": "varies",
        "fanInExpectation": "high"
      },
      "vocabularyCategory": "system",
      "source": "verb-categories.ontology.yaml#categories.registration"
    },
    {
      "id": "testing",
      "name": "Testing",
      "description": "Test-related operations. Mocking, stubbing, assertions.\nShould only appear in test files.\n",
      "canonicalVerbs": [
        "mock",
        "stub",
        "spy",
        "assert",
        "expect"
      ],
      "allowedInLayers": [],
      "forbiddenInLayers": [
        "domain",
        "config"
      ],
      "structuralImplications": {
        "hubIndicator": false,
        "purityViolation": false,
        "fanInExpectation": "none"
      },
      "vocabularyCategory": "system",
      "source": "verb-categories.ontology.yaml#categories.testing"
    }
  ],
  "fileTypes": [
    {
      "id": "Engine",
      "name": "Engine",
      "description": "Decision/evaluation hub that provides central logic consulted by many\nfiles. Requires hub-level fan-in.\nDomain: Decision engines like DecisionEngine.\nService: Completion engines like LLMCompletionEngine.\n",
      "layer": [
        "domain"
      ],
      "tier": "hub",
      "elevatedFrom": [
        "Resolver",
        "Evaluator"
      ],
      "grammar": {
        "fileSuffix": [
          "Engine.ts"
        ],
        "className": "{Domain}Engine",
        "methodPatterns": [
          "^evaluate",
          "^decide",
          "^resolve",
          "^compute"
        ]
      },
      "behavior": {
        "isPure": true,
        "canImportLayers": [
          "domain",
          "config"
        ]
      },
      "source": "file-types.ontology.yaml#types.Engine"
    },
    {
      "id": "Registry",
      "name": "Registry",
      "description": "Central lookup and registration hub.\nService: Module/experience/capability discovery.\nDomain: Type/definition/step-kind lookup.\nInfra: Provider/client registration.\n",
      "layer": [
        "domain"
      ],
      "tier": "hub",
      "elevatedFrom": [
        "Provider",
        "Loader"
      ],
      "grammar": {
        "fileSuffix": [
          "Registry.ts",
          "registry.ts"
        ],
        "className": "{Domain}Registry",
        "methodPatterns": [
          "^register",
          "^get",
          "^resolve",
          "^lookup"
        ]
      },
      "source": "file-types.ontology.yaml#types.Registry"
    },
    {
      "id": "Orchestrator",
      "name": "Orchestrator",
      "description": "Complex flow coordination logic, often stateful per request.\nService: Flow and capability orchestration.\nDomain: State derivation orchestration.\nMid-tier type between Handler and Service. Consider Service if\nfan-in grows.\n",
      "layer": [
        "domain"
      ],
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          "Orchestrator.ts"
        ],
        "className": "{Flow}Orchestrator"
      },
      "source": "file-types.ontology.yaml#types.Orchestrator"
    },
    {
      "id": "Processor",
      "name": "Processor",
      "description": "Pipeline step executor.\nService: Main processing orchestration.\nDomain: Expectation and trajectory processing.\nInfra: Identity and telemetry processing.\n",
      "layer": [
        "domain"
      ],
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          "Processor.ts"
        ],
        "className": "{Entity}Processor"
      },
      "source": "file-types.ontology.yaml#types.Processor"
    },
    {
      "id": "Extractor",
      "name": "Extractor",
      "description": "Extracts structured signals from inputs (often for downstream decisions).\nService: Signal and data extraction from events.\nDomain: Trajectory and state extraction helpers.\n",
      "layer": [
        "domain"
      ],
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          "Extractor.ts"
        ]
      },
      "source": "file-types.ontology.yaml#types.Extractor"
    },
    {
      "id": "Classifier",
      "name": "Classifier",
      "description": "Classifies inputs into categories or intents.\nService: Intent and message classification.\nDomain: Core classification logic.\n",
      "layer": [
        "domain"
      ],
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          "Classifier.ts"
        ]
      },
      "source": "file-types.ontology.yaml#types.Classifier"
    },
    {
      "id": "Resolver",
      "name": "Resolver",
      "description": "Pure logic that prepares context, interprets decisions, or resolves references.\nDomain: DDE context preparation and decision interpretation.\nService: Prompt and path resolution.\nInfra: URL and configuration resolution.\nUI: Module affordance resolution.\nSpoke to Engine. Consider Engine if fan-in grows.\n",
      "layer": [
        "domain"
      ],
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          "Resolver.ts"
        ],
        "className": "{Entity}Resolver"
      },
      "behavior": {
        "isPure": true
      },
      "source": "file-types.ontology.yaml#types.Resolver"
    },
    {
      "id": "Evaluator",
      "name": "Evaluator",
      "description": "Evaluates conditions or rules. Spoke to Engine.\nDomain: Rule and condition evaluation.\nService: Policy and capability evaluation.\nConsider Engine if fan-in grows.\n",
      "layer": [
        "domain"
      ],
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          "Evaluator.ts"
        ],
        "className": "{Entity}Evaluator"
      },
      "behavior": {
        "isPure": true
      },
      "source": "file-types.ontology.yaml#types.Evaluator"
    },
    {
      "id": "Calculator",
      "name": "Calculator",
      "description": "Pure calculation logic. No side effects.\nDomain: Core business calculations.\nService: Comparison and estimation calculations.\nInfra: Utility calculations.\n",
      "layer": [
        "domain"
      ],
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          "Calculator.ts",
          "calculation.ts"
        ]
      },
      "behavior": {
        "isPure": true
      },
      "source": "file-types.ontology.yaml#types.Calculator"
    },
    {
      "id": "Validator",
      "name": "Validator",
      "description": "Complex validation logic. Pure functions.\nDomain: Business rule validation.\nInfra: Schema and data format validation.\n",
      "layer": [
        "domain"
      ],
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          "Validator.ts",
          "validation.ts"
        ]
      },
      "behavior": {
        "isPure": true
      },
      "source": "file-types.ontology.yaml#types.Validator"
    },
    {
      "id": "Transformer",
      "name": "Transformer",
      "description": "Data shape transformation. Pure functions.\nDomain: Core data transformations.\nService: Request/response transformations.\nUI: Display format transformations.\n",
      "layer": [
        "domain"
      ],
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          "Transformer.ts"
        ]
      },
      "behavior": {
        "isPure": true
      },
      "source": "file-types.ontology.yaml#types.Transformer"
    },
    {
      "id": "Factory",
      "name": "Factory",
      "description": "Creates complex domain objects.\n",
      "layer": "domain",
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          "Factory.ts"
        ]
      },
      "source": "file-types.ontology.yaml#types.Factory"
    },
    {
      "id": "Builder",
      "name": "Builder",
      "description": "Step-by-step construction of complex objects.\nDomain: Entity and context builders.\nService: Context pipeline builders.\nConfig: Capability and conductor builders.\n",
      "layer": [
        "domain",
        "config"
      ],
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          "Builder.ts"
        ]
      },
      "source": "file-types.ontology.yaml#types.Builder"
    },
    {
      "id": "Adapter",
      "name": "Adapter",
      "description": "Translates between different formats or interfaces.\nDomain: Surface/Module to Canonical format translation.\nService: Protocol and interface adaptation.\n",
      "layer": [
        "domain"
      ],
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          "Adapter.ts"
        ]
      },
      "source": "file-types.ontology.yaml#types.Adapter"
    },
    {
      "id": "Compiler",
      "name": "Compiler",
      "description": "Compiles definitions into executable artifacts.\n",
      "layer": "domain",
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          "Compiler.ts"
        ]
      },
      "behavior": {
        "isPure": true
      },
      "source": "file-types.ontology.yaml#types.Compiler"
    },
    {
      "id": "Mapper",
      "name": "Mapper",
      "description": "Maps between structured shapes or contexts.\nDomain: Entity and context mapping.\nService: Turn result and output mapping.\n",
      "layer": [
        "domain"
      ],
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          "Mapper.ts"
        ]
      },
      "behavior": {
        "isPure": true
      },
      "source": "file-types.ontology.yaml#types.Mapper"
    },
    {
      "id": "Catalog",
      "name": "Catalog",
      "description": "Defines a curated catalog of entries or capabilities.\nDomain: Capability and contract catalogs.\nConfig: Directive and prompt catalogs.\nInfra: Telemetry contract catalogs.\n",
      "layer": [
        "domain",
        "config"
      ],
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          "Catalog.ts",
          "catalogs.ts"
        ]
      },
      "behavior": {
        "isPure": true
      },
      "source": "file-types.ontology.yaml#types.Catalog"
    },
    {
      "id": "Types",
      "name": "Types",
      "description": "Type definitions and interfaces. No runtime code.\n",
      "layer": "domain",
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          ".types.ts",
          "types.ts",
          "Types.ts"
        ]
      },
      "behavior": {
        "isPure": true
      },
      "source": "file-types.ontology.yaml#types.Types"
    },
    {
      "id": "Schema",
      "name": "Schema",
      "description": "Zod schemas for validation.\nDomain: Core entity and state schemas.\nConfig: Configuration and gate schemas.\n",
      "layer": [
        "domain",
        "config"
      ],
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          ".schema.ts",
          "schema.ts",
          "schemas.ts",
          "Schemas.ts",
          "Schema.ts"
        ]
      },
      "behavior": {
        "isPure": true
      },
      "source": "file-types.ontology.yaml#types.Schema"
    },
    {
      "id": "Index",
      "name": "Index",
      "description": "Barrel file that re-exports module API.\n",
      "layer": "domain",
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          "index.ts",
          "index.tsx",
          "index.js",
          "index.jsx"
        ]
      },
      "behavior": {
        "isPure": true
      },
      "source": "file-types.ontology.yaml#types.Index"
    },
    {
      "id": "Provider",
      "name": "Provider",
      "description": "Provides access to external APIs, static definitions, or action capabilities.\nService: Action providers that implement capability contracts.\nInfra: External API wrappers and data source providers.\nConfig: Static definition providers for flows, threads, etc.\nSpoke to Registry. Consider Registry if fan-in grows.\n",
      "layer": [
        "config"
      ],
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          "Provider.ts"
        ],
        "className": "{Entity}Provider"
      },
      "source": "file-types.ontology.yaml#types.Provider"
    },
    {
      "id": "Context",
      "name": "Context",
      "description": "Scoped state container that flows through a call chain.\nUI: React Context for component state sharing.\nInfra: Request/execution context for tracing and scoped data.\n",
      "layer": [
        "domain"
      ],
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          "Context.tsx",
          "Context.ts",
          "context.ts"
        ]
      },
      "source": "file-types.ontology.yaml#types.Context"
    },
    {
      "id": "Config",
      "name": "Config",
      "description": "Configuration files.\n",
      "layer": "config",
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          ".config.ts",
          "Config.ts"
        ]
      },
      "source": "file-types.ontology.yaml#types.Config"
    },
    {
      "id": "Manifest",
      "name": "Manifest",
      "description": "System or Module manifests.\nConfig: System and module manifests.\nUI: UI experience manifests.\n",
      "layer": [
        "config"
      ],
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          ".manifest.ts",
          "Manifest.ts"
        ]
      },
      "source": "file-types.ontology.yaml#types.Manifest"
    },
    {
      "id": "Constants",
      "name": "Constants",
      "description": "Static constant values.\n",
      "layer": "config",
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          "Constants.ts",
          "constants.ts"
        ]
      },
      "source": "file-types.ontology.yaml#types.Constants"
    },
    {
      "id": "Defaults",
      "name": "Defaults",
      "description": "Default values.\n",
      "layer": "config",
      "tier": "spoke",
      "grammar": {
        "fileSuffix": [
          "Defaults.ts",
          "defaults.ts"
        ]
      },
      "source": "file-types.ontology.yaml#types.Defaults"
    }
  ],
  "forbiddenTypes": [],
  "patterns": [],
  "antiPatterns": [],
  "sequentialPatterns": [
    {
      "id": "providerWrapper",
      "name": "Provider Wrapper Pattern",
      "description": "All external API calls go through providers with consistent\nerror handling, retry logic, and timeout configuration.\n",
      "steps": [
        {
          "step": 1,
          "name": "Configure Options",
          "action": "Set timeout, retries, and other options",
          "example": "{ timeout: 5000, retries: 3, retryDelay: 1000 }"
        },
        {
          "step": 2,
          "name": "Make Request",
          "action": "Call provider method with options",
          "example": "provider.call(input, options)"
        },
        {
          "step": 3,
          "name": "Handle Errors",
          "action": "Provider classifies and handles errors",
          "example": "RetryableError, FatalError, RateLimitError"
        },
        {
          "step": 4,
          "name": "Return Result",
          "action": "Return typed result or throw typed error",
          "example": "return result as ProviderResponse"
        }
      ],
      "details": {
        "constraints": {
          "standardInterface": true,
          "classifyErrors": true,
          "configureTimeout": true
        },
        "errorTypes": {
          "RetryableError": "Temporary failure, can retry",
          "FatalError": "Permanent failure, don't retry",
          "RateLimitError": "Rate limited, back off",
          "TimeoutError": "Request timed out"
        },
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/patterns.invariants.yaml",
            "section": "providerWrapper"
          }
        ]
      },
      "source": "sequential-patterns.ontology.yaml#patterns.providerWrapper"
    }
  ],
  "naming": {
    "principles": {
      "verb_first_methods": {
        "id": "verb_first_methods",
        "name": "Verb-First Methods",
        "description": "Every public method MUST start with a verb that describes the action.\nThe verb connects the method to the file's architectural role.\nThis makes code self-documenting and reveals intent.\n",
        "pattern": "{verb}{Object}",
        "examples": {
          "good": [
            "getUser",
            "calculateScore",
            "validateInput",
            "orchestrateFlow"
          ],
          "bad": [
            "userData",
            "scoreCalculation",
            "user"
          ]
        },
        "verbsByRole": {
          "Repository": {
            "allowed": [
              "find",
              "get",
              "save",
              "delete",
              "update",
              "count",
              "exists"
            ],
            "forbidden": [
              "orchestrate",
              "coordinate"
            ]
          },
          "Service": {
            "allowed": [
              "orchestrate",
              "coordinate",
              "handle",
              "process"
            ],
            "forbidden": [
              "find",
              "save"
            ]
          },
          "Resolver": {
            "allowed": [
              "resolve",
              "decide",
              "determine",
              "calculate",
              "validate",
              "classify"
            ]
          },
          "Transformer": {
            "allowed": [
              "transform",
              "format",
              "parse",
              "map",
              "adapt"
            ]
          },
          "Factory": {
            "allowed": [
              "create",
              "build",
              "generate"
            ]
          },
          "Provider": {
            "allowed": [
              "send",
              "stream",
              "publish",
              "subscribe",
              "fetch",
              "get"
            ]
          },
          "Logger": {
            "allowed": [
              "log",
              "trace",
              "record",
              "track"
            ]
          }
        },
        "antiPatterns": [
          {
            "pattern": "^(data|info|record)[A-Z]",
            "reason": "Method starts with a noun. Use a verb (e.g., 'getUser' not 'userData')."
          },
          {
            "pattern": "^(is|has|can|should)[A-Z].*[A-Z]",
            "note": "Boolean getters (is*, has*, can*) are acceptable exceptions."
          }
        ],
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/naming.invariants.yaml",
            "section": "verb_first"
          }
        ]
      },
      "noun_phrase_classes": {
        "id": "noun_phrase_classes",
        "name": "Noun-Phrase Classes",
        "description": "Class and file names must be Noun Phrases: {Entity}{Role}.\nThe Entity describes the domain concept.\nThe Role describes the architectural type (from taxonomy).\n",
        "pattern": "{Entity}{Role}",
        "examples": {
          "good": [
            "UserResolver",
            "MessageRepository",
            "ChatService",
            "ProgressCalculator"
          ],
          "bad": [
            "Auth",
            "Service",
            "DoSomething"
          ]
        },
        "roleSource": "ontology/file-types.yaml",
        "antiPatterns": [
          {
            "pattern": "^[A-Z][a-z]+$",
            "reason": "Ambiguous. Missing Role suffix (e.g., 'AuthService')."
          },
          {
            "pattern": "^(Resolver|Service|Repository)$",
            "reason": "Ambiguous. Missing Entity prefix (e.g., 'IntentResolver')."
          },
          {
            "pattern": "^(Do|Run|Execute|Handle)[A-Z]",
            "reason": "Verb-based class name. Use noun phrase (e.g., 'MessageHandler')."
          }
        ],
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/naming.invariants.yaml",
            "section": "noun_phrase"
          }
        ]
      },
      "closed_vocabulary": {
        "id": "closed_vocabulary",
        "name": "Closed Vocabulary",
        "description": "The \"Role\" suffix must come from the strict Taxonomy.\nNo inventing new suffixes on the fly. This ensures\nconsistent architectural vocabulary across the codebase.\n",
        "taxonomySource": "ontology/file-types.yaml#types",
        "forbiddenSuffixes": {
          "Engine": {
            "reason": "Ambiguous. Use Service (orchestration) or Resolver (logic).",
            "exceptions": [
              "DecisionEngine"
            ]
          },
          "Processor": {
            "reason": "Ambiguous. Use Handler or Resolver.",
            "alternatives": [
              "Handler",
              "Resolver"
            ]
          },
          "Orchestrator": {
            "reason": "Deprecated. Prefer Service or Coordinator.",
            "alternatives": [
              "Service",
              "Coordinator"
            ]
          },
          "Utility": {
            "reason": "Lazy. Rename by capability.",
            "alternatives": [
              "Formatter",
              "Parser",
              "Calculator"
            ]
          },
          "Utils": {
            "reason": "Lazy. Rename by capability.",
            "alternatives": [
              "Formatters",
              "Parsers"
            ]
          },
          "Helper": {
            "reason": "Lazy. Rename by capability.",
            "alternatives": [
              "Calculator",
              "Transformer",
              "Resolver"
            ]
          },
          "Manager": {
            "reason": "Ambiguous. Use Service (orchestration) or Repository (data access).",
            "alternatives": [
              "Service",
              "Repository"
            ]
          },
          "Wrapper": {
            "reason": "Generic, non-descriptive.",
            "alternatives": [
              "Adapter",
              "Provider"
            ]
          },
          "Base": {
            "reason": "Only for actual base classes.",
            "note": "Acceptable if truly an abstract base class."
          }
        },
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/naming.invariants.yaml",
            "section": "closed_vocabulary"
          },
          {
            "base": "runtime",
            "path": "ontology/file-types.yaml",
            "section": "forbiddenTypes"
          }
        ]
      },
      "no_noise": {
        "id": "no_noise",
        "name": "No-Noise Principle",
        "description": "Remove words that add no semantic value.\nEvery word in an identifier should contribute meaning.\n",
        "forbiddenTerms": [
          {
            "term": "Data",
            "reason": "Redundant. DataRepository -> Repository",
            "example": [
              "UserData -> User",
              "DataService -> Service"
            ]
          },
          {
            "term": "Info",
            "reason": "Redundant. UserInfo -> User",
            "example": [
              "UserInfo -> User"
            ]
          },
          {
            "term": "Object",
            "reason": "Redundant. UserObject -> User",
            "example": [
              "UserObject -> User",
              "DataObject -> Entity"
            ]
          },
          {
            "term": "Impl",
            "reason": "Implementation detail. ServiceImpl -> Service",
            "example": [
              "ServiceImpl -> Service"
            ]
          },
          {
            "term": "Abstract",
            "reason": "Only use if actually abstract",
            "note": "Acceptable for actual abstract base classes."
          },
          {
            "term": "Simple",
            "reason": "Subjective and uninformative"
          },
          {
            "term": "Basic",
            "reason": "Subjective and uninformative"
          },
          {
            "term": "New",
            "reason": "Temporary and will become stale"
          },
          {
            "term": "Old",
            "reason": "Temporary and will become stale"
          }
        ],
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/naming.invariants.yaml",
            "section": "no_noise"
          }
        ]
      },
      "antonym_consistency": {
        "id": "antonym_consistency",
        "name": "Antonym Consistency",
        "description": "Use consistent pairs of opposites across the system.\nDon't mix synonyms (e.g., create/destroy vs create/delete).\n",
        "canonicalPairs": [
          [
            "create",
            "delete"
          ],
          [
            "add",
            "remove"
          ],
          [
            "start",
            "stop"
          ],
          [
            "open",
            "close"
          ],
          [
            "show",
            "hide"
          ],
          [
            "enable",
            "disable"
          ],
          [
            "connect",
            "disconnect"
          ],
          [
            "mount",
            "unmount"
          ],
          [
            "subscribe",
            "unsubscribe"
          ],
          [
            "register",
            "unregister"
          ],
          [
            "load",
            "unload"
          ],
          [
            "begin",
            "end"
          ],
          [
            "acquire",
            "release"
          ],
          [
            "push",
            "pop"
          ],
          [
            "enqueue",
            "dequeue"
          ]
        ],
        "avoid": [
          {
            "pair": [
              "create",
              "remove"
            ],
            "reason": "Inconsistent. Use create/delete or add/remove."
          },
          {
            "pair": [
              "start",
              "end"
            ],
            "reason": "Ambiguous. Use start/stop or begin/end."
          },
          {
            "pair": [
              "create",
              "destroy"
            ],
            "reason": "Inconsistent. Use create/delete."
          }
        ],
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/naming.invariants.yaml",
            "section": "antonyms"
          }
        ]
      },
      "capability_aligned_entity": {
        "id": "capability_aligned_entity",
        "name": "Capability-Aligned Entity",
        "description": "The Entity prefix in {Entity}{Role} must describe WHAT the file does,\nderived from its primary capabilities. Generic prefixes cause confusion\nabout a file's purpose.\n\nA file with capability \"orchestrates:incremental scan\" should be named\n\"IncrementalScanService\", not just \"ScanService\".\n",
        "derivationRules": [
          {
            "source": "primary capability noun",
            "target": "Entity prefix",
            "description": "The noun phrase from capabilities should appear in the filename",
            "example": {
              "capability": "orchestrates:file analysis",
              "good": "FileAnalysisService",
              "bad": "AnalysisService"
            }
          },
          {
            "source": "capability qualifiers",
            "target": "Entity prefix qualifiers",
            "description": "Qualifying adjectives from capabilities should be preserved",
            "example": {
              "capability": "orchestrates:incremental scan",
              "good": "IncrementalScanService",
              "bad": "ScanService"
            }
          }
        ],
        "vagueEntities": [
          {
            "entity": "Scan",
            "reason": "Scan what? Use 'IncrementalScan', 'FullScan', 'ChangedFileScan'"
          },
          {
            "entity": "Analysis",
            "reason": "Analyze what? Use 'FileAnalysis', 'DependencyAnalysis', 'ImpactAnalysis'"
          },
          {
            "entity": "Process",
            "reason": "Process what? Name should describe the processed entity"
          },
          {
            "entity": "Handle",
            "reason": "Handle what? Name should describe the handled entity"
          },
          {
            "entity": "Manage",
            "reason": "Manage what? Use specific entity name"
          },
          {
            "entity": "Execute",
            "reason": "Execute what? Name should describe the executed operation"
          },
          {
            "entity": "Data",
            "reason": "Data of what? Use specific domain name"
          },
          {
            "entity": "Item",
            "reason": "Item of what? Use specific entity name"
          }
        ],
        "detection": {
          "algorithm": "1. Extract primary capabilities (first 3, highest confidence)\n2. Parse noun phrases from capabilities\n3. Extract Entity prefix from filename\n4. Check if Entity aligns with capability nouns\n5. Flag if Entity is vague AND capability has more specific noun\n",
          "severity": "medium",
          "evaluator": "naming.capabilityAlignedEntity"
        },
        "examples": {
          "good": [
            {
              "name": "FileAnalysisService",
              "capability": "orchestrates:file analysis",
              "reason": "Entity 'FileAnalysis' matches capability noun 'file analysis'"
            },
            {
              "name": "IncrementalScanService",
              "capability": "orchestrates:incremental scan",
              "reason": "Entity 'IncrementalScan' matches capability noun 'incremental scan'"
            },
            {
              "name": "FullScanService",
              "capability": "orchestrates:full scan",
              "reason": "Entity 'FullScan' matches capability noun 'full scan'"
            },
            {
              "name": "DependencyGraphBuilder",
              "capability": "builds:dependency graph",
              "reason": "Entity 'DependencyGraph' matches capability noun 'dependency graph'"
            }
          ],
          "bad": [
            {
              "name": "ScanService",
              "capability": "orchestrates:incremental scan",
              "reason": "Entity 'Scan' is vague; capability specifies 'incremental scan'",
              "suggested": "IncrementalScanService"
            },
            {
              "name": "AnalysisService",
              "capability": "orchestrates:file analysis",
              "reason": "Entity 'Analysis' is vague; capability specifies 'file analysis'",
              "suggested": "FileAnalysisService"
            },
            {
              "name": "ProcessService",
              "capability": "orchestrates:event processing",
              "reason": "Entity 'Process' is vague; capability specifies 'event processing'",
              "suggested": "EventProcessingService"
            }
          ]
        },
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/naming.invariants.yaml",
            "section": "capability_aligned_entity"
          }
        ]
      }
    },
    "pathNaming": {
      "description": "File and directory naming must consider:\n1. What your ecosystem's tooling and import rules expect\n2. Cross-platform portability (Linux + macOS + Windows + CI + Git)\n3. Readability in paths, URLs, and terminals\n",
      "nonNegotiables": [
        {
          "rule": "Be consistent within the repo",
          "reason": "Mixing styles causes 'works on my machine' path bugs"
        },
        {
          "rule": "Prefer lowercase for paths unless ecosystem strongly expects otherwise",
          "reason": "Case-only renames are a classic cross-platform Git headache"
        },
        {
          "rule": "Avoid spaces and special punctuation",
          "reason": "Shell, URLs, and build tools will eventually break"
        },
        {
          "rule": "Don't start names with hyphen (-)",
          "reason": "Looks like a CLI flag"
        },
        {
          "rule": "If it becomes an import/module name, use what the language can import",
          "reason": "kebab-case often loses here (can't import file-name in most languages)"
        }
      ],
      "importFrictionTest": {
        "description": "Before choosing a case for code files, ask:\n1. Will I ever need to `import` this by name (not just by path string)?\n2. Does the language allow this character/case pattern cleanly?\n",
        "guidance": {
          "file_becomes_identifier": {
            "description": "File name maps to an exported class/function/type",
            "typescript": "PascalCase for classes, camelCase acceptable",
            "python": "snake_case (mandatory for modules)",
            "java_csharp": "PascalCase (class name == file name)"
          },
          "file_is_just_path": {
            "description": "File is referenced by path string only (configs, assets, docs)",
            "preferred": "kebab-case",
            "reason": "Most readable in URLs, terminals, and plain text"
          }
        }
      },
      "caseStyles": {
        "kebab-case": {
          "description": "Words separated by hyphens: user-profile, account-settings",
          "use_when": [
            "Names appear in URLs, routes, or web-facing paths",
            "Frontend/web where filenames are path strings",
            "Documentation and content files",
            "YAML/JSON configuration files",
            "Directory names (default choice)"
          ],
          "avoid_when": [
            "Language treats filename as identifier that cannot contain hyphens",
            "File name maps directly to an import/export"
          ],
          "examples": {
            "good": [
              "user-profile/",
              "api-reference.md",
              "layers.yaml"
            ],
            "bad": [
              "UserProfile/ (for configs)",
              "apiReference.md"
            ]
          }
        },
        "snake_case": {
          "description": "Words separated by underscores: data_loader, feature_store",
          "use_when": [
            "Python modules and packages",
            "Ruby scripts",
            "Filenames that become identifiers in underscore-preferring languages"
          ],
          "avoid_when": [
            "Web-oriented repo where kebab-case is standard"
          ],
          "examples": {
            "good": [
              "data_loader.py",
              "feature_engineering/"
            ]
          }
        },
        "PascalCase": {
          "description": "Each word capitalized: UserService, OrderRepository",
          "use_when": [
            "TypeScript/JavaScript files exporting a class",
            "React components",
            "Java/C# where class name must match file name",
            "File name maps to primary exported identifier"
          ],
          "avoid_when": [
            "Config files, assets, documentation",
            "Files that don't export a primary class"
          ],
          "examples": {
            "good": [
              "ChatService.ts",
              "UserProfileCard.tsx"
            ],
            "bad": [
              "chatService.ts",
              "user-profile-card.tsx (if exporting class)"
            ]
          }
        },
        "camelCase": {
          "description": "First word lowercase, rest capitalized: getUserData",
          "use_when": [
            "Variable and function names (not files)",
            "Some JS/TS codebases use for non-class files"
          ],
          "avoid_when": [
            "File and directory names (harder to scan, error-prone)"
          ],
          "note": "Fine for identifiers. For paths, it's 'you can, but why?'"
        },
        "SCREAMING_SNAKE_CASE": {
          "description": "All caps with underscores: DATABASE_URL",
          "use_when": [
            "Environment variables",
            "Constants in code"
          ],
          "never_for": [
            "Files or directories"
          ]
        }
      }
    },
    "directoryNaming": {
      "description": "Directory names should be lowercase kebab-case by default.\nThis ensures maximum portability and readability.\n",
      "default": "kebab-case",
      "patterns": {
        "standard_directories": {
          "convention": "kebab-case",
          "examples": [
            "user-service/",
            "api-handlers/",
            "core-config/"
          ]
        },
        "next_app_router": {
          "convention": "kebab-case or (grouping)",
          "examples": [
            "app/(web)/",
            "app/api/v1/",
            "app/(auth)/"
          ],
          "note": "Next.js route groups use parentheses"
        },
        "component_directories": {
          "convention": "kebab-case",
          "examples": [
            "components/user-profile/",
            "components/chat-input/"
          ],
          "note": "Even if components are PascalCase, directories are kebab-case"
        }
      },
      "avoid": [
        {
          "pattern": "PascalCase directories",
          "reason": "Case sensitivity issues across platforms",
          "exception": "Only if ecosystem strongly requires (rare)"
        },
        {
          "pattern": "camelCase directories",
          "reason": "Harder to read in paths"
        },
        {
          "pattern": "Spaces in directory names",
          "reason": "Shell and URL escaping issues"
        }
      ]
    },
    "fileNamingByExtension": {
      "description": "File naming conventions vary by file type based on the \"import friction\"\ntest - whether the filename becomes an identifier or is just a path.\n",
      "typescript": {
        "description": "TypeScript files - naming depends on what they export",
        "class_exports": {
          "convention": "PascalCase",
          "pattern": "{Entity}{Role}.ts",
          "reason": "Filename matches exported class name",
          "examples": [
            "ChatService.ts",
            "UserRepository.ts",
            "MessageHandler.ts"
          ]
        },
        "component_exports": {
          "convention": "PascalCase",
          "pattern": "{ComponentName}.tsx",
          "reason": "Filename matches exported component",
          "examples": [
            "ChatInput.tsx",
            "UserProfileCard.tsx"
          ]
        },
        "hook_exports": {
          "convention": "camelCase with use prefix",
          "pattern": "use{Purpose}.ts",
          "reason": "React hook naming convention",
          "examples": [
            "useCanonicalState.ts",
            "useChatStream.ts"
          ]
        },
        "metadata_files": {
          "convention": "PascalCase.descriptor",
          "pattern": "{Domain}.{descriptor}.ts",
          "allowed_descriptors": [
            "types",
            "schema",
            "config",
            "manifest",
            "generated",
            "validation",
            "constants"
          ],
          "reason": "Domain prefix matches concept, descriptor indicates purpose",
          "examples": {
            "good": [
              "Message.types.ts",
              "Prompt.manifest.ts",
              "User.schema.ts",
              "Chat.config.ts"
            ],
            "bad": [
              "types.ts",
              "schema.ts",
              "config.ts"
            ]
          },
          "antiPatterns": [
            {
              "pattern": "^(types|schema|config|constants)\\.ts$",
              "reason": "Bare bucket file. Add domain prefix: {Domain}.types.ts"
            },
            {
              "pattern": "^(Types|Schema|Config)\\.ts$",
              "reason": "PascalCase bucket without domain. Use: {Domain}.types.ts"
            }
          ],
          "exceptions": [
            {
              "file": "index.ts",
              "reason": "Required by module resolution conventions"
            },
            {
              "file": "handler.ts",
              "reason": "Convention for route handlers in Next.js app router"
            },
            {
              "file": "route.ts",
              "reason": "Required by Next.js app router"
            }
          ]
        },
        "entry_points": {
          "convention": "lowercase",
          "examples": [
            "index.ts",
            "handler.ts",
            "route.ts"
          ],
          "reason": "Convention-driven, not identifier-driven"
        }
      },
      "yaml": {
        "description": "YAML files are paths, not imports - use kebab-case",
        "convention": "kebab-case",
        "reason": "Config files are referenced by path, never imported as identifiers",
        "patterns": {
          "standard": "{domain}.yaml",
          "with_qualifier": "{domain}-{qualifier}.yaml",
          "invariants": "{domain}.invariants.yaml"
        },
        "examples": {
          "good": [
            "layers.yaml",
            "file-types.yaml",
            "verb-categories.yaml",
            "anti-patterns.yaml",
            "layers.invariants.yaml"
          ],
          "bad": [
            "Layers.yaml",
            "FileTypes.yaml",
            "file_types.yaml"
          ]
        }
      },
      "json": {
        "description": "JSON files are paths - use kebab-case or ecosystem convention",
        "convention": "kebab-case or ecosystem standard",
        "examples": {
          "standard": [
            "package.json",
            "tsconfig.json"
          ],
          "custom": [
            "taxonomy.json",
            "state.json"
          ]
        }
      },
      "markdown": {
        "description": "Documentation files - kebab-case or SCREAMING for special files",
        "patterns": {
          "standard": "kebab-case",
          "special": "SCREAMING_SNAKE_CASE for repo-root files"
        },
        "examples": {
          "standard": [
            "getting-started.md",
            "api-reference.md",
            "migration-plan.md"
          ],
          "special": [
            "README.md",
            "CLAUDE.md",
            "CHANGELOG.md",
            "MIGRATION-PLAN.md"
          ]
        }
      }
    },
    "fileNaming": {
      "conventions": {
        "description": "File naming conventions for architectural roles and artifacts.\nFiles should be named to reveal their purpose and role.\n",
        "patterns": {
          "Service": "{Domain}Service.ts",
          "Factory": "{Domain}Factory.ts",
          "Handler": "handler.ts or {action}.handler.ts",
          "Repository": "{Domain}Repository.ts",
          "Provider": "{External}Provider.ts",
          "Command": "{CommandName}.command.ts or commands/{CommandName}.ts",
          "Hook": "use{Purpose}.ts",
          "Component": "{PascalCase}.tsx",
          "Types": "{Domain}.types.ts or Types.ts",
          "Schema": "{Domain}.schema.ts or Schema.ts",
          "Config": "{Domain}.config.ts or Config.ts",
          "Manifest": "{Domain}.manifest.ts",
          "Constants": "Constants.ts or {Domain}.constants.ts",
          "Defaults": "Defaults.ts or {Domain}.defaults.ts",
          "Index": "index.ts",
          "Resolver": "{Domain}Resolver.ts",
          "Calculator": "{Domain}Calculator.ts",
          "Validator": "{Domain}Validator.ts",
          "Transformer": "{Domain}Transformer.ts",
          "Adapter": "{Domain}Adapter.ts",
          "Builder": "{Domain}Builder.ts",
          "Cache": "{Domain}Cache.ts",
          "Logger": "{Domain}Logger.ts",
          "Publisher": "{Domain}Publisher.ts",
          "Loader": "{Domain}Loader.ts"
        },
        "dotNotation": {
          "description": "Use {Domain}.{descriptor}.ts when the file describes metadata\ninstead of exporting a primary class/function.\n",
          "allowedDescriptors": [
            "types",
            "schema",
            "config",
            "manifest",
            "generated",
            "validation",
            "constants"
          ],
          "pattern": "{PascalCasePrefix}.{descriptor}.ts",
          "examples": {
            "good": [
              "Message.types.ts",
              "Prompt.manifest.ts",
              "ProgressInsights.schema.ts"
            ],
            "bad": [
              "prompt.manifest.ts",
              "Prompt.Adaptive.manifest.ts"
            ]
          }
        },
        "maxSegments": {
          "production": 2,
          "test": 3
        },
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/naming.invariants.yaml",
            "section": "file_naming"
          },
          {
            "base": "runtime",
            "path": "ontology/naming-rules.yaml",
            "section": "fileNaming"
          }
        ]
      },
      "rules": {
        "enforcePascalCase": true,
        "ignorePatterns": [
          "**/node_modules/**",
          "**/dist/**",
          "**/build/**",
          "**/coverage/**",
          "**/__tests__/**",
          "**/tests/**",
          "**/__mocks__/**",
          "**/mocks/**",
          "**/*.test.*",
          "**/*.spec.*",
          "**/*.mock.*"
        ],
        "allowLowercasePatterns": [
          "**/index.ts",
          "**/index.tsx",
          "**/*.types.ts",
          "**/*.schema.ts",
          "**/*.config.ts",
          "**/*.manifest.ts",
          "**/*.generated.ts",
          "**/*.validation.ts",
          "**/use*.ts",
          "**/use*.tsx",
          "**/derive*.ts",
          "**/calc*.ts",
          "**/handler.ts",
          "**/*.handler.ts",
          "**/*.command.ts",
          "**/*.command.tsx",
          "**/with*.ts",
          "**/with*.tsx",
          "**/*.provider.ts",
          "**/utils.ts",
          "**/client.ts",
          "**/defaults.ts",
          "**/validation.ts",
          "**/constants.ts",
          "**/helpers.ts",
          "**/affordances.ts",
          "**/affordances.tsx",
          "**/scopes.ts",
          "**/surfaces.ts",
          "**/types.ts",
          "**/schema.ts",
          "**/patch.ts",
          "**/budgets.ts",
          "**/summary.ts",
          "**/catalog.ts",
          "**/state.ts",
          "**/narrative.ts",
          "**/*Schemas.ts",
          "**/*Validator.ts",
          "**/*Readers.ts",
          "**/*Loaders.ts",
          "**/*Loader.ts",
          "**/*Key.ts",
          "**/*Policy.ts",
          "**/*Serialize.ts",
          "**/*Ordering.ts",
          "**/*Override.ts",
          "**/*Lease.ts",
          "**/*Candidate.ts",
          "**/*Helpers.ts",
          "**/*Prompt.ts",
          "**/*Instructions.ts",
          "**/*Scores.ts",
          "**/*Limits.ts",
          "**/*Logging.ts",
          "**/*Cache.ts",
          "**/*Intent.ts",
          "**/*Context.ts",
          "**/*Client.ts",
          "**/*Decision.ts",
          "**/*State.ts",
          "**/*Plan.ts",
          "**/*Handler.ts",
          "**/*Id.ts",
          "**/*.client.ts",
          "**/*.client.tsx",
          "**/*.turnPlan.ts",
          "**/fast_classifier_questions.ts",
          "cli.ts",
          "compare-models.ts",
          "test-*.ts",
          "scripts/*.mjs",
          "lib/*.ts",
          "domain/analysis/*.ts",
          "domain/ontology/*.ts"
        ],
        "requireExportMatchesFile": false,
        "maxSegments": {
          "production": 2,
          "test": 3
        }
      },
      "systemDirectory": {
        "enforce": false,
        "roots": [],
        "matchMode": "contains-segment"
      }
    },
    "artifacts": {
      "description": "Canonical names for core system data structures.\nThese names should be used consistently throughout the codebase.\n",
      "coreArtifacts": {
        "TurnPlan": {
          "description": "The strategy directive for a turn",
          "location": "@/core/types"
        },
        "InteractionEvent": {
          "description": "The canonical input event",
          "location": "@/core/types"
        },
        "CanonicalState": {
          "description": "The persisted state",
          "location": "@/core/types"
        },
        "DerivedState": {
          "description": "The computed view (never persisted)",
          "location": "@/core/types"
        },
        "ExtendedState": {
          "description": "CanonicalState + DerivedState combined",
          "location": "@/core/types"
        }
      },
      "sources": [
        {
          "base": "runtime",
          "path": "invariants/naming.invariants.yaml",
          "section": "artifacts"
        }
      ]
    },
    "exports": {
      "principles": [
        {
          "id": "default_for_components",
          "rule": "Default export for React components",
          "reason": "Allows flexible naming on import"
        },
        {
          "id": "named_for_utilities",
          "rule": "Named exports for utilities, types, and services",
          "reason": "Enables tree shaking and explicit imports"
        },
        {
          "id": "reexport_from_index",
          "rule": "Re-export from index.ts for public module API",
          "reason": "Clean public interface"
        },
        {
          "id": "import_from_source",
          "rule": "Import internal types from their definition files",
          "reason": "Avoid circular dependencies through index.ts"
        }
      ],
      "sources": [
        {
          "base": "runtime",
          "path": "invariants/naming.invariants.yaml",
          "section": "exports"
        }
      ]
    },
    "capabilityNaming": {
      "enforcePluralVerbs": true,
      "verbsSource": "taxonomy",
      "allowUnknownVerbs": false
    },
    "layerRoleCompatibility": {
      "enforce": true,
      "allowedRoles": {
        "ui": [
          "Component",
          "Hook",
          "Context",
          "Store",
          "Index",
          "Types",
          "Config",
          "Handler",
          "Manifest",
          "Page",
          "Cache",
          "Transformer",
          "Resolver"
        ],
        "route": [
          "Route",
          "Handler",
          "Command",
          "Index",
          "Types",
          "Schema",
          "Adapter"
        ],
        "service": [
          "Service",
          "Orchestrator",
          "Coordinator",
          "Processor",
          "Handler",
          "Router",
          "Executor",
          "Extractor",
          "Classifier",
          "Factory",
          "Builder",
          "Registry",
          "Initializer",
          "Validator",
          "Resolver",
          "Provider",
          "Schema",
          "Cache",
          "Context",
          "Loader",
          "Adapter",
          "Evaluator",
          "Publisher",
          "Calculator",
          "Catalog",
          "Compiler",
          "Defaults",
          "Logger",
          "Transformer",
          "Tracker",
          "Mapper",
          "Index",
          "Types",
          "Config"
        ],
        "domain": [
          "Calculator",
          "Validator",
          "Transformer",
          "Factory",
          "Builder",
          "Resolver",
          "Derivation",
          "Helper",
          "Analyzer",
          "Formatter",
          "Compiler",
          "Mapper",
          "Catalog",
          "Service",
          "Orchestrator",
          "Engine",
          "Evaluator",
          "Extractor",
          "Classifier",
          "Context",
          "Loader",
          "Defaults",
          "Index",
          "Types",
          "Schema",
          "Config",
          "Constants"
        ],
        "infra": [
          "Repository",
          "Provider",
          "Cache",
          "Logger",
          "Publisher",
          "Adapter",
          "Handler",
          "Factory",
          "Registry",
          "Loader",
          "Service",
          "Builder",
          "Orchestrator",
          "Processor",
          "Context",
          "Validator",
          "Catalog",
          "Calculator",
          "Executor",
          "Index",
          "Types",
          "Config"
        ],
        "config": [
          "Config",
          "Manifest",
          "Constants",
          "Defaults",
          "Types",
          "Schema",
          "Loader",
          "Resolver",
          "Factory",
          "Index"
        ]
      }
    },
    "roleCollision": {
      "enforce": true,
      "uniqueRoles": [
        "Repository",
        "Store"
      ],
      "warnMultiple": [
        "Service",
        "Orchestrator"
      ]
    },
    "namingExceptions": [],
    "sources": [
      "naming-conventions.ontology.yaml#principles",
      "naming-conventions.ontology.yaml#pathNaming",
      "naming-conventions.ontology.yaml#directoryNaming",
      "naming-conventions.ontology.yaml#fileNamingByExtension",
      "naming-conventions.ontology.yaml#fileNaming",
      "naming-conventions.ontology.yaml#artifacts",
      "naming-conventions.ontology.yaml#exports",
      "naming-rules.ontology.yaml#systemDirectory",
      "naming-rules.ontology.yaml#fileNaming",
      "naming-rules.ontology.yaml#capabilityNaming",
      "naming-rules.ontology.yaml#layerRoleCompatibility",
      "naming-rules.ontology.yaml#roleCollision",
      "file-types.ontology.yaml#namingExceptions"
    ]
  }
} as ArchitectureGrammarPackInput;
