// GENERATED by the WO-4 architecture grammar port, restructured to the
// three-tier model by WO-4.1 (see grammar-port-manifest.json and the
// amendment memo). Classic content is migration-source DATA; classic code
// is never imported. Edit through the operator pathway, not by hand.
import type { ArchitectureGrammarPackInput } from "../schema.js";

export const grammarBasePack: ArchitectureGrammarPackInput = {
  "id": "grammar-base",
  "version": "2.0.0",
  "kind": "base",
  "tier": "base",
  "description": "Minimal universal grammar canon: only content that earned base tier with a per-row argument in grammar-port-manifest.json. The layered-school grammar lives in the archetype packs and backs findings only where ratified.",
  "provenance": {
    "migratedFrom": "codebase-intel-classic ontology/ (verified 2026-06-10)",
    "note": "restructured to three tiers by the WO-4.1 amendment; see the amendment memo"
  },
  "layers": [],
  "verbCategories": [],
  "fileTypes": [],
  "forbiddenTypes": [
    {
      "id": "Manager",
      "reason": "Ambiguous. Use 'Service' (orchestration) or 'Repository' (data access).",
      "alternatives": [
        "Service",
        "Repository"
      ],
      "source": "file-types.ontology.yaml#forbiddenTypes.Manager"
    },
    {
      "id": "Util",
      "reason": "Too generic. Rename based on capability.",
      "alternatives": [
        "Formatter",
        "Parser",
        "Calculator"
      ],
      "source": "file-types.ontology.yaml#forbiddenTypes.Util"
    },
    {
      "id": "Utils",
      "reason": "Too generic. Rename based on capability.",
      "alternatives": [
        "Formatters",
        "Parsers"
      ],
      "source": "file-types.ontology.yaml#forbiddenTypes.Utils"
    },
    {
      "id": "Helper",
      "reason": "Too generic. Rename based on capability.",
      "alternatives": [
        "Calculator",
        "Transformer",
        "Resolver"
      ],
      "source": "file-types.ontology.yaml#forbiddenTypes.Helper"
    },
    {
      "id": "Helpers",
      "reason": "Too generic. Rename based on capability.",
      "alternatives": [
        "Calculators",
        "Transformers"
      ],
      "source": "file-types.ontology.yaml#forbiddenTypes.Helpers"
    },
    {
      "id": "Wrapper",
      "reason": "Generic, non-descriptive.",
      "alternatives": [
        "Adapter",
        "Provider"
      ],
      "source": "file-types.ontology.yaml#forbiddenTypes.Wrapper"
    },
    {
      "id": "Base",
      "reason": "Only for actual base classes. Otherwise too generic.",
      "alternatives": [],
      "source": "file-types.ontology.yaml#forbiddenTypes.Base"
    }
  ],
  "patterns": [],
  "antiPatterns": [
    {
      "id": "consoleLogging",
      "name": "Console Logging in Production",
      "category": "observability",
      "dont": "console.log(debug)",
      "do": "Use telemetry system",
      "reason": "Console logging is not captured in production observability.\nUse the telemetry system for structured logging that integrates\nwith monitoring and alerting.\n",
      "examples": {
        "bad": "async process(input) {\n  console.log('Processing:', input);  // Lost in production!\n  console.error('Error:', err);       // No alerting!\n}\n",
        "good": "async process(input) {\n  telemetry.log('chat.process.start', { input });\n  telemetry.error('chat.process.error', { error: err });\n}\n"
      },
      "details": {
        "detectable": true,
        "detectionRules": [
          {
            "evaluator": "observability.console",
            "patterns": [
              "console\\.(log|warn|error|debug|info)\\("
            ]
          }
        ],
        "exceptions": [
          {
            "path": "tools/**",
            "reason": "CLI tools may use console"
          },
          {
            "path": "**/*.test.*",
            "reason": "Tests may use console"
          },
          {
            "path": "scripts/**",
            "reason": "Operational scripts intentionally write to stdout/stderr"
          },
          {
            "path": "cli.ts",
            "reason": "Primary CLI entrypoint uses stdout/stderr for user-facing output"
          },
          {
            "path": "compare-models.ts",
            "reason": "Standalone report script emits formatted console output"
          },
          {
            "path": "test-*.ts",
            "reason": "Top-level harness scripts are treated as non-production diagnostics"
          },
          {
            "path": "lib/host-integration.ts",
            "reason": "Contains embedded host-script templates with console output"
          }
        ],
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/anti-patterns.invariants.yaml",
            "section": "consoleLogging"
          }
        ]
      },
      "source": "anti-patterns.ontology.yaml#antiPatterns.consoleLogging"
    },
    {
      "id": "deleteFeatureDuringRefactor",
      "name": "Delete Feature During Refactor",
      "category": "process",
      "dont": "Delete feature during refactor",
      "do": "Extract and improve; preserve functionality",
      "reason": "Refactoring should preserve behavior. Removing features while\nrefactoring mixes two concerns and makes rollback difficult.\nExtract first, then decide separately whether to keep.\n",
      "examples": {
        "bad": "// \"While I'm refactoring ChatService, I'll remove the\n// legacy voice support since we don't use it much...\"\n",
        "good": "// Step 1: Refactor ChatService, preserve all features\n// Step 2: Separate PR to deprecate voice if needed\n// Step 3: Separate PR to remove after deprecation period\n"
      },
      "details": {
        "detectable": false,
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/anti-patterns.invariants.yaml",
            "section": "deleteFeatureDuringRefactor"
          }
        ]
      },
      "source": "anti-patterns.ontology.yaml#antiPatterns.deleteFeatureDuringRefactor"
    },
    {
      "id": "ambiguousSuffix",
      "name": "Ambiguous Type Suffix",
      "category": "naming",
      "dont": "Use Manager, Util, Helper, Wrapper suffixes",
      "do": "Use specific suffixes from taxonomy (Service, Repository, Calculator, etc.)",
      "reason": "Ambiguous suffixes like \"Manager\" don't communicate architectural role.\nUse specific suffixes that indicate what the file does and where it\nbelongs in the architecture.\n",
      "examples": {
        "bad": [
          "UserManager.ts",
          "StringUtils.ts",
          "DataHelper.ts"
        ],
        "good": [
          "UserService.ts",
          "StringFormatter.ts",
          "DataTransformer.ts"
        ]
      },
      "details": {
        "detectable": true,
        "detectionRules": [
          {
            "evaluator": "naming.forbiddenSuffix",
            "patterns": [
              "Manager\\.ts$",
              "Util(s)?\\.ts$",
              "Helper(s)?\\.ts$",
              "Wrapper\\.ts$"
            ]
          }
        ],
        "violates": [
          "closed_vocabulary",
          "noun_phrase_classes"
        ],
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/naming.invariants.yaml",
            "section": "closed_vocabulary"
          },
          {
            "base": "runtime",
            "path": "ontology/file-types.yaml",
            "section": "forbiddenTypes"
          }
        ]
      },
      "source": "anti-patterns.ontology.yaml#antiPatterns.ambiguousSuffix"
    }
  ],
  "sequentialPatterns": [],
  "hubClassification": {
    "definiteHubPercentile": 95,
    "probableHubPercentile": 80,
    "probableHubRatio": 1,
    "minDefiniteHubFanIn": 3,
    "minProbableHubFanIn": 2,
    "downgradeRules": {
      "Service": "Handler",
      "Engine": "Resolver",
      "Registry": "Provider"
    },
    "detectionRule": "taxonomy.hubSuffixRequiresHubStatus",
    "source": "file-types.ontology.yaml#hubClassification"
  }
} as ArchitectureGrammarPackInput;
