// GENERATED by the WO-4 architecture grammar port from
// legacy-source ontology directory (migration-source DATA;
// classic code is never imported). Every entry carries its classic source
// reference; the row-by-row audit lives in
// packages/capability-ontology/grammar-port-manifest.json.
// Edit through the operator pathway (overrides / vocabulary review), not by
// hand-amending ported values.
import type { ArchitectureGrammarPackInput } from "../schema.js";

export const grammarProjectOverlayExample: ArchitectureGrammarPackInput = {
  "id": "grammar-project-overlay-example",
  "version": "1.0.0",
  "kind": "overlay",
  "description": "Reference overlay pack: project-specific law from the classic source project (DDE instantiation, gate patterns, streaming invariants, module-registry rules). Never applied automatically; adopters copy this shape for their own law.",
  "provenance": {
    "migratedFrom": "legacy-source ontology/ (project-specific entries)",
    "note": "ships as the reference implementation of the overlay model"
  },
  "patterns": [
    {
      "id": "declarative_gate",
      "name": "Declarative Gate Pattern",
      "category": "configuration",
      "definition": "Business decisions are expressed in YAML gates; computation stays in\nTypeScript. Configuration-driven behavior separates policy (what to do)\nfrom mechanism (how to do it).\n",
      "structuralSignals": [
        "Business rules in YAML gate files",
        "Calculations in domain TypeScript files",
        "Services call DDE.evaluate(), not hardcoded if-else"
      ],
      "details": {
        "allowedIn": [
          "config",
          "service"
        ],
        "forbiddenIn": [
          "domain"
        ],
        "detectionRules": [
          {
            "evaluator": "services.businessLogic",
            "checks": [
              "Hardcoded business logic in services",
              "Business decisions without DDE call"
            ]
          }
        ],
        "enforced": true,
        "relatedPatterns": [
          "single_source_of_truth",
          "unidirectional_flow"
        ],
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/architectural-patterns.invariants.yaml",
            "section": "declarativeGate"
          }
        ]
      },
      "source": "patterns.ontology.yaml#patterns.declarative_gate"
    },
    {
      "id": "idempotent_turn",
      "name": "Idempotent Turn Pattern",
      "category": "reliability",
      "definition": "Use client_turn_id / assistant_turn_key for exactly-once semantics.\nRetries never duplicate side effects; conversations are resumable.\n",
      "structuralSignals": [
        "client_turn_id in request",
        "assistant_turn_key in response",
        "Idempotency check before side effects",
        "Resumable conversation state"
      ],
      "details": {
        "allowedIn": [
          "route",
          "service"
        ],
        "forbiddenIn": [],
        "constraints": {
          "requireTurnId": true,
          "checkBeforeSideEffect": true
        },
        "enforced": true,
        "relatedPatterns": [
          "streaming_invariant",
          "single_source_of_truth"
        ],
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/architectural-patterns.invariants.yaml",
            "section": "idempotentTurn"
          }
        ]
      },
      "source": "patterns.ontology.yaml#patterns.idempotent_turn"
    },
    {
      "id": "streaming_invariant",
      "name": "Streaming Invariant",
      "category": "reliability",
      "definition": "Exactly-once SSE done event; no DB writes during streaming;\norder preserved. Streaming responses complete exactly once\nwith guaranteed event ordering.\n",
      "structuralSignals": [
        "Single done event per stream",
        "DB writes after stream completes",
        "Events emitted in order",
        "Error events on failure"
      ],
      "details": {
        "allowedIn": [
          "service",
          "infra"
        ],
        "forbiddenIn": [],
        "constraints": {
          "exactlyOnceDone": true,
          "noDbWritesDuringStream": true,
          "orderPreserved": true
        },
        "enforced": true,
        "relatedPatterns": [
          "idempotent_turn"
        ],
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/architectural-patterns.invariants.yaml",
            "section": "streamingInvariant"
          }
        ]
      },
      "source": "patterns.ontology.yaml#patterns.streaming_invariant"
    },
    {
      "id": "rule_versioning",
      "name": "Rule Versioning Pattern",
      "category": "configuration",
      "definition": "Gates carry versions and manifest order; higher priority wins.\nVersion-controlled gate definitions with deterministic\nevaluation order.\n",
      "structuralSignals": [
        "Version field in gate files",
        "Priority field determines order",
        "Higher priority overrides lower",
        "Manifest tracks gate order"
      ],
      "details": {
        "priorityRanges": {
          "core": "100-199",
          "experience": "200-399",
          "module": "400-599",
          "override": "800-999"
        },
        "allowedIn": [
          "config"
        ],
        "forbiddenIn": [],
        "constraints": {
          "requireVersion": true,
          "requirePriority": true,
          "deterministicOrder": true
        },
        "enforced": true,
        "relatedPatterns": [
          "declarative_gate"
        ],
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/architectural-patterns.invariants.yaml",
            "section": "ruleVersioning"
          }
        ]
      },
      "source": "patterns.ontology.yaml#patterns.rule_versioning"
    }
  ],
  "antiPatterns": [
    {
      "id": "manualDDEInstantiation",
      "name": "Manual DDE Instantiation",
      "category": "architecture",
      "dont": "new DDE() in service",
      "do": "Inject DDE via constructor",
      "reason": "Services should receive dependencies via constructor injection.\nSelf-instantiation makes testing hard and couples services to\nconcrete implementations.\n",
      "examples": {
        "bad": "class ChatService {\n  private dde = new DecisionEngine();  // Self-instantiation!\n\n  async process() {\n    return this.dde.evaluate(state);\n  }\n}\n",
        "good": "class ChatService {\n  constructor(private dde: DecisionEngine) {}  // Injected!\n\n  async process() {\n    return this.dde.evaluate(state);\n  }\n}\n"
      },
      "details": {
        "detectable": true,
        "detectionRules": [
          {
            "evaluator": "services.businessLogic",
            "patterns": [
              "new DecisionEngine\\(",
              "new DDE\\(",
              "createDDE\\(\\)"
            ]
          }
        ],
        "violates": [
          "dependencyInjection"
        ],
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/anti-patterns.invariants.yaml",
            "section": "manualDDEInstantiation"
          }
        ]
      },
      "source": "anti-patterns.ontology.yaml#antiPatterns.manualDDEInstantiation"
    },
    {
      "id": "coreImportsModule",
      "name": "Core Imports Experience/Module Directly",
      "category": "boundaries",
      "dont": "import { X } from 'experiences/*' or 'experiences/*/modules/*' in core",
      "do": "Use ExperienceRegistry or ModuleRegistry",
      "reason": "Core should never import from experiences or modules directly. This creates hard\ncoupling and breaks the plugin architecture. Use registries\nfor discovery and thin adapters for delegation.\n",
      "examples": {
        "bad": "// In core/services/chat/ChatService.ts\nimport { AssessmentHandler } from '@/experiences/career/modules/assessments';  // Direct!\n\nclass ChatService {\n  async process() {\n    const handler = new AssessmentHandler();  // Coupled!\n  }\n}\n",
        "good": "// In core/services/chat/ChatService.ts\nimport { moduleRegistry } from '@/core/modules';\n\nclass ChatService {\n  async process() {\n    const handler = moduleRegistry.get('assessments') ?? noOpHandler;\n  }\n}\n"
      },
      "details": {
        "detectable": true,
        "detectionRules": [
          {
            "evaluator": "imports.moduleBoundary",
            "patterns": [
              "from ['\"]@/experiences/",
              "import.*from.*experiences/"
            ]
          }
        ],
        "violates": [
          "thinAdapter",
          "provider_isolation"
        ],
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/anti-patterns.invariants.yaml",
            "section": "coreImportsModule"
          }
        ]
      },
      "source": "anti-patterns.ontology.yaml#antiPatterns.coreImportsModule"
    },
    {
      "id": "directDerivedAccess",
      "name": "Direct Derived State Access",
      "category": "boundaries",
      "dont": "derived.modules.assessments?.riasecCompleted",
      "do": "getAssessmentsDerived(derived).riasecCompleted",
      "reason": "Direct access to module-namespaced derived state couples core to\nmodule structure. Use helper functions that handle missing modules\ngracefully and maintain type safety.\n",
      "examples": {
        "bad": "// Direct access couples core to module structure\nconst riasecDone = derived.modules.assessments?.riasecCompleted;\nconst lccActive = derived.modules.lcc?.isActive;\n",
        "good": "// Helper functions decouple and handle missing modules\nimport { getAssessmentsDerived, getLccDerived } from '@/core/domain/state/derived/Helpers';\n\nconst riasecDone = getAssessmentsDerived(derived).riasecCompleted;\nconst lccActive = getLccDerived(derived).isActive;\n"
      },
      "details": {
        "detectable": true,
        "detectionRules": [
          {
            "evaluator": "state.directAccess",
            "patterns": [
              "derived\\.modules\\.",
              "state\\.modules\\."
            ]
          }
        ],
        "violates": [
          "derivedHelper"
        ],
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/anti-patterns.invariants.yaml",
            "section": "directDerivedAccess"
          }
        ]
      },
      "source": "anti-patterns.ontology.yaml#antiPatterns.directDerivedAccess"
    },
    {
      "id": "dbWriteDuringStream",
      "name": "Database Write During Stream",
      "category": "streaming",
      "dont": "DB write during SSE stream",
      "do": "Write after stream completes",
      "reason": "Writing to database during streaming can cause partial state if\nthe stream is interrupted. Wait until stream completes to ensure\natomic state updates.\n",
      "examples": {
        "bad": "for await (const chunk of stream) {\n  await this.repo.saveChunk(chunk);  // Risky during stream!\n  encoder.encode(chunk);\n}\n",
        "good": "const chunks = [];\nfor await (const chunk of stream) {\n  chunks.push(chunk);\n  encoder.encode(chunk);\n}\n// Write after stream completes\nawait this.repo.saveResponse(chunks.join(''));\n"
      },
      "details": {
        "detectable": false,
        "violates": [
          "streaming_invariant"
        ],
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/anti-patterns.invariants.yaml",
            "section": "dbWriteDuringStream"
          }
        ]
      },
      "source": "anti-patterns.ontology.yaml#antiPatterns.dbWriteDuringStream"
    }
  ],
  "sequentialPatterns": [
    {
      "id": "streaming",
      "name": "Streaming Pattern",
      "description": "All streaming uses SSE with structured events and guaranteed completion.\nSingle connection, exactly-once done event.\n",
      "steps": [
        {
          "step": 1,
          "name": "Establish Connection",
          "action": "Create SSE stream",
          "example": "new TransformStream()"
        },
        {
          "step": 2,
          "name": "Send Structured Events",
          "action": "Emit typed events through stream",
          "example": "encoder.encode(`event: delta\\ndata: ${JSON.stringify(data)}\\n\\n`)"
        },
        {
          "step": 3,
          "name": "Send Done Event",
          "action": "Exactly-once completion signal",
          "example": "encoder.encode(`event: done\\ndata: {}\\n\\n`)"
        },
        {
          "step": 4,
          "name": "Close Stream",
          "action": "Clean up resources",
          "example": "controller.close()"
        }
      ],
      "details": {
        "constraints": {
          "exactlyOnceDone": true,
          "noDbWritesDuringStream": true,
          "orderPreserved": true
        },
        "eventTypes": {
          "delta": "Incremental content update",
          "done": "Stream completion signal",
          "error": "Error occurred during stream",
          "metadata": "Non-content data"
        },
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/patterns.invariants.yaml",
            "section": "streaming"
          }
        ]
      },
      "source": "sequential-patterns.ontology.yaml#patterns.streaming"
    },
    {
      "id": "derivedHelper",
      "name": "Derived Helper Pattern",
      "description": "Never access module state directly - use getXDerived() helpers.\nThis decouples core from module structure.\n",
      "steps": [
        {
          "step": 1,
          "name": "Import Helper",
          "action": "Import the module-specific helper",
          "example": "import { getAssessmentsDerived } from '@/core/domain/state/derived/Helpers'"
        },
        {
          "step": 2,
          "name": "Call Helper",
          "action": "Get module-specific derived state",
          "example": "const assessments = getAssessmentsDerived(derived)"
        },
        {
          "step": 3,
          "name": "Access Properties",
          "action": "Access properties on the returned object",
          "example": "assessments.riasecCompleted"
        }
      ],
      "details": {
        "constraints": {
          "noDirectAccess": true,
          "alwaysUseHelper": true
        },
        "examples": {
          "good": "import { getAssessmentsDerived } from '@/core/domain/state/derived/Helpers';\nconst assessments = getAssessmentsDerived(derived);\nconst riasecDone = assessments.riasecCompleted;\n",
          "bad": "// Direct access couples core to module structure!\nconst riasecDone = derived.modules.assessments?.riasecCompleted;\n"
        },
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/patterns.invariants.yaml",
            "section": "derivedHelper"
          }
        ]
      },
      "source": "sequential-patterns.ontology.yaml#patterns.derivedHelper"
    },
    {
      "id": "structuredPayload",
      "name": "Structured Payload Pattern",
      "description": "Module communication uses typed structured payloads via InteractionRouter.\nEnsures version compatibility and clear contracts.\n",
      "steps": [
        {
          "step": 1,
          "name": "Create Payload",
          "action": "Build structured payload object",
          "example": "{ moduleKey: 'assessments', type: 'answer', version: '1.0', data: {...} }"
        },
        {
          "step": 2,
          "name": "Route via InteractionRouter",
          "action": "Send payload through router",
          "example": "interactionRouter.route(payload)"
        },
        {
          "step": 3,
          "name": "Module Handles",
          "action": "Target module processes payload",
          "example": "assessmentsProvider.handleInteraction(payload)"
        }
      ],
      "details": {
        "payloadSchema": {
          "moduleKey": "string - target module identifier",
          "type": "string - interaction type",
          "version": "string - schema version",
          "data": "object - type-specific payload"
        },
        "constraints": {
          "alwaysVersioned": true,
          "typedPayload": true,
          "routeThroughRouter": true
        },
        "sources": [
          {
            "base": "runtime",
            "path": "invariants/patterns.invariants.yaml",
            "section": "structuredPayload"
          }
        ]
      },
      "source": "sequential-patterns.ontology.yaml#patterns.structuredPayload"
    }
  ]
} as ArchitectureGrammarPackInput;
