import type { SemanticFileUnderstandingSeverity } from "@rekon/kernel-repo-model";

export const SEMANTIC_DEBT_PROMPT_VERSION = "debt-judge-v3";
export const SEMANTIC_DEBT_COERCION_VERSION = "debt-coercion-v3";
export const SEMANTIC_DEBT_ELIGIBILITY_VERSION = "debt-eligibility-v3";
export const SEMANTIC_DEBT_MAX_PROMPT_CHARS = 24000;

export type SemanticDebtEligibilityReason =
  | "eligible"
  | "non-production"
  | "declaration-file"
  | "generated-file"
  | "data-artifact"
  | "prompt-truncated"
  | "binary-content"
  | "empty-content";

export type SemanticDebtEligibilityDecision = {
  eligible: boolean;
  version: typeof SEMANTIC_DEBT_ELIGIBILITY_VERSION;
  reasons: SemanticDebtEligibilityReason[];
};

export const SEMANTIC_DEBT_JUDGMENT_JSON_SCHEMA: Record<string, unknown> = {
  type: "object",
  additionalProperties: false,
  properties: {
    concerns: {
      type: "array",
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          type: {
            type: "string",
            enum: ["architecture", "tech_debt", "dead_code", "lint", "stub"],
          },
          severity: { type: "string", enum: ["low", "medium", "high"] },
          description: { type: "string" },
          line: { type: ["integer", "null"] },
        },
        required: ["type", "severity", "description", "line"],
      },
    },
  },
  required: ["concerns"],
};

export type SemanticDebtAdapterConcern = {
  type?: string;
  severity?: string;
  description?: string;
  line?: number;
};

export type SemanticDebtAdapterResult = {
  concerns?: SemanticDebtAdapterConcern[];
  provider?: string;
  model?: string;
  warnings?: string[];
};

export function evaluateSemanticDebtEligibility(input: {
  path: string;
  content: string;
}): SemanticDebtEligibilityDecision {
  const reasons: SemanticDebtEligibilityReason[] = [];
  const normalized = input.path.replaceAll("\\", "/").toLowerCase();
  if (/(^|\/)(?:__tests__|tests?|specs?|fixtures?|examples?)(\/|$)/u.test(normalized)
    || /\.(?:test|spec)\.[cm]?[jt]sx?$/u.test(normalized)
    || /\.mdx?$/u.test(normalized)) {
    reasons.push("non-production");
  }
  if (/\.d\.[cm]?ts$/u.test(normalized)) reasons.push("declaration-file");
  const structuredData = /\.(?:json|ya?ml)$/u.test(normalized);
  if (structuredData && /(^|\/)(?:artifacts?|data|logs?|outputs?|recordings?|reports?|results?|snapshots?)(\/|$)/u.test(normalized)) {
    reasons.push("data-artifact");
  }
  if (input.content.length > SEMANTIC_DEBT_MAX_PROMPT_CHARS) reasons.push("prompt-truncated");
  if (input.content.includes("\u0000")) reasons.push("binary-content");
  if (input.content.trim().length === 0) reasons.push("empty-content");
  const header = input.content.split("\n").slice(0, 12).join("\n");
  const hiddenOperationalPath = normalized
    .split("/")
    .some((segment) => segment.length > 1 && segment.startsWith("."));
  if (hiddenOperationalPath || /@generated\b|AUTO-GENERATED|DO NOT EDIT|^\s*\/\/.*Generated by /imu.test(header)) {
    reasons.push("generated-file");
  }
  return reasons.length === 0
    ? { eligible: true, version: SEMANTIC_DEBT_ELIGIBILITY_VERSION, reasons: ["eligible"] }
    : { eligible: false, version: SEMANTIC_DEBT_ELIGIBILITY_VERSION, reasons };
}

export const SEMANTIC_CONCERN_TYPES = ["architecture", "tech_debt", "dead_code", "lint", "stub"] as const;
export type SemanticConcernType = (typeof SEMANTIC_CONCERN_TYPES)[number];

export type SemanticDebtJudgmentAdapter = (input: {
  filePath: string;
  fileText: string;
  language?: string;
}) => Promise<SemanticDebtAdapterResult>;

export type SemanticDebtConcernCoerced = {
  type: SemanticConcernType;
  severity: SemanticFileUnderstandingSeverity;
  description: string;
  line?: number;
  pattern?: string;
  included: boolean;
};

export function buildSemanticDebtJudgmentPrompt(input: {
  filePath: string;
  fileText: string;
  language?: string;
}): string {
  const languageLine = input.language ? `Language: ${input.language}` : "";
  const sourceLines = input.fileText.split(/\r?\n/u);
  const lineNumberWidth = String(Math.max(1, sourceLines.length)).length;
  const numberedSource = sourceLines
    .map((line, index) => `${String(index + 1).padStart(lineNumberWidth, " ")} | ${line}`)
    .join("\n");
  return [
    "Review this source file for repository intelligence concerns.",
    "",
    "Concern types:",
    "- architecture: module boundary, layering, ownership, or dependency direction problems.",
    "- tech_debt: implementation debt that should be scheduled or corrected.",
    "- dead_code: unused exports, unreachable code, or obsolete implementation surface.",
    "- lint: localized style or correctness issues that a static check could enforce.",
    "- stub: placeholder implementation, incomplete scaffolding, or fake behavior.",
    "",
    "Severity rubric:",
    "- high: likely to cause defects, security exposure, data corruption, or repeated engineering risk.",
    "- medium: meaningful maintainability, reliability, or type-safety debt with clear evidence.",
    "- low: small but concrete cleanup with direct evidence in the file.",
    "",
    "Common tech_debt patterns:",
    "- Unreachable branches or stale code paths whose lack of use is visible in this file.",
    '- Type-safety gaps such as "as any", non-null assertions, weak unknown handling, or string values where a union belongs.',
    "- Missing error handling, catch blocks that hide failures, or fallback behavior that masks broken states.",
    "- Hardcoded values such as tokens, keys, origins, URLs, feature names, or configuration constants.",
    "- Duplication, copy/paste branching, or repeated logic that should be centralized.",
    "- Fallback logic that silently chooses defaults without evidence.",
    "- @deprecated fields or deprecated API usage.",
    "",
    "Rules:",
    "- Judge only what is visible in this file.",
    "- Do not infer runtime behavior, hidden call sites, or external configuration.",
    "- Do not report lint concerns. Repository-native static checks own unused imports, formatting, and similar diagnostics.",
    "- Do not report missing runtime validation for typed database, repository, framework, or provider values unless this file visibly accepts an untrusted value at that boundary.",
    "- Verify every named symbol against the complete file before claiming it is unused or missing.",
    "- Security or credential-exposure concerns require a visible exposure path such as logging, persistence, serialization, or URL construction; handling a token is not itself exposure.",
    "- Give the exact numbered line containing the evidence by copying its numeric prefix. If no exact evidence line exists, return no concern.",
    "- Do not report concerns for type-only files, generated files, factory wiring, or simple dependency composition unless there is concrete debt in the file.",
    "- Keep architecture concerns labeled architecture, dead-code concerns labeled dead_code, lint concerns labeled lint, and placeholder concerns labeled stub.",
    "- Use tech_debt only for concrete debt in the file, not for speculative redesign ideas.",
    "- Return no concerns when the file is clean.",
    "- Return ONLY one JSON object. No markdown fences, prose, or comments.",
    "",
    'Output contract: { "concerns": [ { "type": "architecture|tech_debt|dead_code|lint|stub", "severity": "low|medium|high", "description": string, "line": number } ] }',
    'When clean: { "concerns": [] }',
    "",
    languageLine,
    `File path: ${input.filePath}`,
    "Numbered file contents (line prefixes are metadata, not source):",
    numberedSource,
  ]
    .filter((line) => line.length > 0)
    .join("\n");
}

export function categorizeDebtPattern(description: string): string | null {
  const text = description.toLowerCase();
  if (text.includes("hardcoded") || text.includes("hard-coded")) return "hardcoded_values";
  if (
    text.includes("type assertion")
    || text.includes("as any")
    || text.includes("typed as any")
    || text.includes("any annotation")
    || text.includes("explicit any")
    || text.includes("uses `any`")
    || text.includes("using `any`")
  ) return "type_assertion";
  if (text.includes("error handling") || text.includes("catch") || text.includes("try/catch")) return "error_handling";
  if (text.includes("magic number") || text.includes("magic string")) return "magic_values";
  if (text.includes("inline css") || text.includes("inline style")) return "inline_styles";
  if (text.includes("deprecated")) return "deprecated";
  if (text.includes("unknown type") || text.includes("weak type")) return "weak_types";
  if (text.includes("fallback")) return "fallback_logic";
  if (text.includes("comment") && (text.includes("todo") || text.includes("fixme") || text.includes("hack"))) {
    return "todo_comments";
  }
  if (text.includes("duplication") || text.includes("duplicate")) return "duplication";
  return null;
}

export function hasStrongDebtSignal(description: string): boolean {
  const text = description.toLowerCase();
  if (
    text.includes("must not") ||
    text.includes("never ") ||
    text.includes("deprecated") ||
    text.includes("unsafe") ||
    text.includes("security") ||
    text.includes("todo") ||
    text.includes("fixme") ||
    text.includes("hack") ||
    text.includes("bypass") ||
    text.includes("violation")
  ) {
    return true;
  }

  const hardcoded = text.includes("hardcoded") || text.includes("hard-coded");
  if (!hardcoded) return false;
  return ["api", "url", "origin", "token", "key", "secret", "credential", "cors"].some((word) =>
    text.includes(word),
  );
}

export function hasSpeculativeDebtSignal(description: string): boolean {
  const text = description.toLowerCase();
  return (
    text.includes("consider ") ||
    text.includes("could ") ||
    text.includes("may ") ||
    text.includes("might ") ||
    text.includes("verify ") ||
    text.includes("suggest") ||
    text.includes("if this abstraction layer is necessary") ||
    text.includes("if this layer is necessary") ||
    text.includes("if part of public api")
  );
}

export function shouldIncludeDebtConcern(input: {
  severity: SemanticFileUnderstandingSeverity;
  description: string;
}): boolean {
  const text = input.description.toLowerCase();
  const strong = hasStrongDebtSignal(input.description);
  const assumesUnseenValidation = (
    text.includes("database value")
    || text.includes("persisted value")
    || text.includes("repository value")
    || text.includes("provider value")
  ) && (
    text.includes("without runtime validation")
    || text.includes("instead of being narrowed or validated")
    || text.includes("invalid or newly introduced persisted value")
    || text.includes("unexpected persisted")
  );
  if (assumesUnseenValidation) return false;
  if (text.includes("may indicate") || text.includes("might indicate")) return false;
  if (input.severity === "low" && !strong) return false;
  if (hasSpeculativeDebtSignal(input.description) && !strong) return false;
  return true;
}

export function coerceDebtConcerns(adapterResult: SemanticDebtAdapterResult): SemanticDebtConcernCoerced[] {
  if (!adapterResult || !Array.isArray(adapterResult.concerns)) return [];
  const out: SemanticDebtConcernCoerced[] = [];

  for (const concern of adapterResult.concerns) {
    if (!concern || !isSemanticConcernType(concern.type)) continue;
    const description = typeof concern.description === "string" ? concern.description.trim() : "";
    if (description.length === 0) continue;
    const severity: SemanticFileUnderstandingSeverity =
      concern.severity === "high" || concern.severity === "medium" || concern.severity === "low"
        ? concern.severity
        : "low";
    const pattern = categorizeDebtPattern(description);
    out.push({
      type: concern.type,
      severity,
      description,
      ...(typeof concern.line === "number" && Number.isInteger(concern.line) && concern.line > 0
        ? { line: concern.line }
        : {}),
      ...(pattern ? { pattern } : {}),
      included: concern.type !== "lint" && shouldIncludeDebtConcern({ severity, description }),
    });
  }

  return out;
}

function isSemanticConcernType(value: unknown): value is SemanticConcernType {
  return typeof value === "string" && (SEMANTIC_CONCERN_TYPES as readonly string[]).includes(value);
}
