import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { cp, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, relative, resolve } from "node:path";
import test from "node:test";

const repoRoot = resolve(new URL("../..", import.meta.url).pathname);
const cliPath = join(repoRoot, "packages/cli/dist/index.js");
const exampleRoot = join(repoRoot, "examples/simple-js-ts");

test("agent-contract export writes AGENTS.rekon.md from the latest agent-contract Publication", async () => {
  await withFixture(async (root) => {
    runCli(["refresh", "--root", root, "--json"]);
    runCli(["publish", "agent-contract", "--root", root, "--json"]);

    const result = JSON.parse(
      runCli([
        "agent-contract",
        "export",
        "--root",
        root,
        "--output",
        "AGENTS.rekon.md",
        "--json",
      ]).stdout,
    );

    assert.equal(result.wrote, true);
    assert.equal(result.protectedPath, false);
    assert.equal(result.forced, false);
    assert.equal(result.outputPath, "AGENTS.rekon.md");
    assert.equal(result.absolutePath, join(root, "AGENTS.rekon.md"));
    assert.equal(result.publicationRef.type, "Publication");
    assert.ok(typeof result.publicationRef.id === "string" && result.publicationRef.id.length > 0);
    assert.equal(result.publicationRef.schemaVersion, "0.1.0");

    const written = await readFile(join(root, "AGENTS.rekon.md"), "utf8");
    assert.ok(written.length > 0);
  });
});

test("exported file includes the generated preamble citing the source Publication", async () => {
  await withFixture(async (root) => {
    runCli(["refresh", "--root", root, "--json"]);
    runCli(["publish", "agent-contract", "--root", root, "--json"]);

    const result = JSON.parse(
      runCli([
        "agent-contract",
        "export",
        "--root",
        root,
        "--output",
        "AGENTS.rekon.md",
        "--json",
      ]).stdout,
    );

    const written = await readFile(join(root, "AGENTS.rekon.md"), "utf8");

    assert.ok(written.startsWith("<!--"));
    assert.ok(written.includes("Generated by Rekon from .rekon artifacts."));
    assert.ok(written.includes(`Source publication: Publication:${result.publicationRef.id}`));
    assert.ok(written.includes("Do not treat this file as canonical truth."));
    assert.ok(written.includes("Canonical truth lives in .rekon/artifacts."));
    assert.ok(written.includes("Regenerate with: rekon publish agent-contract && rekon agent-contract export --output AGENTS.rekon.md"));
  });
});

test("exported file includes the original agent-contract Publication content", async () => {
  await withFixture(async (root) => {
    runCli(["refresh", "--root", root, "--json"]);
    const publishResult = JSON.parse(
      runCli(["publish", "agent-contract", "--root", root, "--json"]).stdout,
    );
    const publicationRef = publishResult.artifacts.find((ref) => ref.type === "Publication");
    const publication = JSON.parse(
      await readFile(join(root, publicationRef.path), "utf8"),
    );

    runCli([
      "agent-contract",
      "export",
      "--root",
      root,
      "--output",
      "AGENTS.rekon.md",
      "--json",
    ]);

    const written = await readFile(join(root, "AGENTS.rekon.md"), "utf8");

    assert.ok(written.includes(publication.content));
    assert.ok(written.includes("# Rekon Agent Operating Contract"));
  });
});

test("agent-contract export refuses to overwrite an existing file without --force", async () => {
  await withFixture(async (root) => {
    runCli(["refresh", "--root", root, "--json"]);
    runCli(["publish", "agent-contract", "--root", root, "--json"]);
    runCli([
      "agent-contract",
      "export",
      "--root",
      root,
      "--output",
      "AGENTS.rekon.md",
      "--json",
    ]);

    const second = runCliExpectFailure([
      "agent-contract",
      "export",
      "--root",
      root,
      "--output",
      "AGENTS.rekon.md",
      "--json",
    ]);

    assert.ok(
      second.stderr.includes("Refusing to overwrite existing file AGENTS.rekon.md without --force."),
      `expected refusal message, got stderr: ${second.stderr}`,
    );
  });
});

test("agent-contract export overwrites an existing file when --force is provided", async () => {
  await withFixture(async (root) => {
    runCli(["refresh", "--root", root, "--json"]);
    runCli(["publish", "agent-contract", "--root", root, "--json"]);
    await writeFile(join(root, "AGENTS.rekon.md"), "stale placeholder\n", "utf8");

    const result = JSON.parse(
      runCli([
        "agent-contract",
        "export",
        "--root",
        root,
        "--output",
        "AGENTS.rekon.md",
        "--force",
        "--json",
      ]).stdout,
    );

    assert.equal(result.wrote, true);
    assert.equal(result.forced, true);
    assert.equal(result.protectedPath, false);
    assert.equal(
      result.message,
      "Overwrote existing file because --force was provided.",
    );

    const written = await readFile(join(root, "AGENTS.rekon.md"), "utf8");
    assert.ok(!written.includes("stale placeholder"));
    assert.ok(written.includes("# Rekon Agent Operating Contract"));
  });
});

test("agent-contract export refuses to overwrite AGENTS.md without --force", async () => {
  await withFixture(async (root) => {
    runCli(["refresh", "--root", root, "--json"]);
    runCli(["publish", "agent-contract", "--root", root, "--json"]);

    const result = runCliExpectFailure([
      "agent-contract",
      "export",
      "--root",
      root,
      "--output",
      "AGENTS.md",
      "--json",
    ]);

    assert.ok(
      result.stderr.includes(
        "Refusing whole-file export to protected agent instruction file AGENTS.md.",
      ),
      `expected protected-path refusal, got stderr: ${result.stderr}`,
    );
  });
});

test("agent-contract export refuses AGENTS.md even with --force", async () => {
  await withFixture(async (root) => {
    runCli(["refresh", "--root", root, "--json"]);
    runCli(["publish", "agent-contract", "--root", root, "--json"]);

    const result = runCliExpectFailure([
      "agent-contract", "export", "--root", root, "--output", "AGENTS.md", "--force", "--json",
    ]);
    assert.match(result.stderr, /Use `rekon agent-instructions sync`/);
  });
});

test("agent-contract export refuses to overwrite CLAUDE.md without --force", async () => {
  await withFixture(async (root) => {
    runCli(["refresh", "--root", root, "--json"]);
    runCli(["publish", "agent-contract", "--root", root, "--json"]);

    const result = runCliExpectFailure([
      "agent-contract",
      "export",
      "--root",
      root,
      "--output",
      "CLAUDE.md",
      "--json",
    ]);

    assert.ok(
      result.stderr.includes(
        "Refusing whole-file export to protected agent instruction file CLAUDE.md.",
      ),
      `expected protected-path refusal for CLAUDE.md, got stderr: ${result.stderr}`,
    );
  });
});

test("agent-contract export refuses to overwrite .cursor/rules/*.md without --force", async () => {
  await withFixture(async (root) => {
    runCli(["refresh", "--root", root, "--json"]);
    runCli(["publish", "agent-contract", "--root", root, "--json"]);

    const result = runCliExpectFailure([
      "agent-contract",
      "export",
      "--root",
      root,
      "--output",
      ".cursor/rules/rekon.md",
      "--json",
    ]);

    assert.ok(
      result.stderr.includes(
        "Refusing whole-file export to protected agent instruction file .cursor/rules/rekon.md.",
      ),
      `expected protected-path refusal for .cursor/rules path, got stderr: ${result.stderr}`,
    );
  });
});

test("agent-contract export refuses to overwrite .github/copilot-instructions.md without --force", async () => {
  await withFixture(async (root) => {
    runCli(["refresh", "--root", root, "--json"]);
    runCli(["publish", "agent-contract", "--root", root, "--json"]);

    const result = runCliExpectFailure([
      "agent-contract",
      "export",
      "--root",
      root,
      "--output",
      ".github/copilot-instructions.md",
      "--json",
    ]);

    assert.ok(
      result.stderr.includes(
        "Refusing whole-file export to protected agent instruction file .github/copilot-instructions.md.",
      ),
      `expected protected-path refusal for copilot path, got stderr: ${result.stderr}`,
    );
  });
});

test("agent-contract export refuses paths that resolve outside the repo root", async () => {
  await withFixture(async (root) => {
    runCli(["refresh", "--root", root, "--json"]);
    runCli(["publish", "agent-contract", "--root", root, "--json"]);

    const outsideAbsolute = join(tmpdir(), "rekon-export-outside.md");
    const outsideResult = runCliExpectFailure([
      "agent-contract",
      "export",
      "--root",
      root,
      "--output",
      outsideAbsolute,
      "--json",
    ]);

    assert.ok(
      outsideResult.stderr.includes("must resolve inside the repo root"),
      `expected outside-root refusal for absolute path, got stderr: ${outsideResult.stderr}`,
    );

    const relativeEscape = runCliExpectFailure([
      "agent-contract",
      "export",
      "--root",
      root,
      "--output",
      "../escape.md",
      "--json",
    ]);

    assert.ok(
      relativeEscape.stderr.includes("must resolve inside the repo root"),
      `expected outside-root refusal for relative escape, got stderr: ${relativeEscape.stderr}`,
    );
  });
});

test("agent-contract export auto-publishes when no agent-contract Publication exists yet", async () => {
  await withFixture(async (root) => {
    runCli(["refresh", "--root", root, "--json"]);

    const result = JSON.parse(
      runCli([
        "agent-contract",
        "export",
        "--root",
        root,
        "--output",
        "AGENTS.rekon.md",
        "--json",
      ]).stdout,
    );

    assert.equal(result.wrote, true);
    assert.equal(result.publicationRef.type, "Publication");
    assert.ok(result.publicationRef.id.startsWith("agent-contract-"));

    const written = await readFile(join(root, "AGENTS.rekon.md"), "utf8");
    assert.ok(written.includes("# Rekon Agent Operating Contract"));
  });
});

test("rekon publish agent-contract does not modify the managed root AGENTS.md", async () => {
  await withFixture(async (root) => {
    runCli(["refresh", "--root", root, "--json"]);
    const before = await readFile(join(root, "AGENTS.md"), "utf8");
    runCli(["publish", "agent-contract", "--root", root, "--json"]);
    const after = await readFile(join(root, "AGENTS.md"), "utf8");

    assert.equal(after, before, "publish agent-contract must not modify root AGENTS.md");
  });
});

test("agent-contract export JSON output includes publicationRef, outputPath, absolutePath, forced, protectedPath, wrote", async () => {
  await withFixture(async (root) => {
    runCli(["refresh", "--root", root, "--json"]);
    runCli(["publish", "agent-contract", "--root", root, "--json"]);

    const result = JSON.parse(
      runCli([
        "agent-contract",
        "export",
        "--root",
        root,
        "--output",
        "AGENTS.rekon.md",
        "--json",
      ]).stdout,
    );

    assert.ok("publicationRef" in result);
    assert.ok("outputPath" in result);
    assert.ok("absolutePath" in result);
    assert.ok("forced" in result);
    assert.ok("protectedPath" in result);
    assert.ok("wrote" in result);
    assert.equal(typeof result.outputPath, "string");
    assert.equal(typeof result.absolutePath, "string");
    assert.equal(typeof result.forced, "boolean");
    assert.equal(typeof result.protectedPath, "boolean");
    assert.equal(typeof result.wrote, "boolean");
    assert.equal(result.publicationRef.type, "Publication");
    assert.equal(typeof result.publicationRef.id, "string");
    assert.equal(typeof result.publicationRef.schemaVersion, "string");
  });
});

test("agent-contract export requires --output", async () => {
  await withFixture(async (root) => {
    runCli(["refresh", "--root", root, "--json"]);
    runCli(["publish", "agent-contract", "--root", root, "--json"]);

    const result = runCliExpectFailure([
      "agent-contract",
      "export",
      "--root",
      root,
      "--json",
    ]);

    assert.ok(
      result.stderr.includes("rekon agent-contract export requires --output <path>."),
      `expected missing-output error, got stderr: ${result.stderr}`,
    );
  });
});

// ---------- helpers ----------

async function withFixture(callback) {
  const root = await mkdtemp(join(tmpdir(), "rekon-agent-contract-export-"));

  try {
    await cp(exampleRoot, root, {
      recursive: true,
      filter(source) {
        return !relative(exampleRoot, source).split(/[\\/]/).includes(".rekon");
      },
    });
    await callback(root);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
}

function runCli(args) {
  const result = spawnSync(process.execPath, [cliPath, ...args], {
    cwd: repoRoot,
    encoding: "utf8",
  });
  assert.equal(result.status, 0, result.stderr || result.stdout);
  return result;
}

function runCliExpectFailure(args) {
  const result = spawnSync(process.execPath, [cliPath, ...args], {
    cwd: repoRoot,
    encoding: "utf8",
  });
  assert.notEqual(result.status, 0, `expected non-zero exit, got stdout: ${result.stdout}`);
  return result;
}
