// WO-15 behavioral tests: the four dead_code exemption classes (each
// counted - the WO-13 transparency pattern), the operator-topology
// compile fix with eligibility-gated detection, and the no-override
// regression.

import assert from "node:assert/strict";
import { join, resolve } from "node:path";
import test from "node:test";

const repoRoot = resolve(new URL("../..", import.meta.url).pathname);
const policy = await import(join(repoRoot, "packages/capability-policy/dist/index.js"));
const ontology = await import(join(repoRoot, "packages/capability-ontology/dist/grammar/index.js"));
const jsts = await import(join(repoRoot, "packages/capability-js-ts/dist/index.js"));

const file = (path) => ({ kind: "file", subject: path, value: {} });
const exp = (path, name) => ({ kind: "export", subject: path, value: { name, kind: "const" } });
const newStats = () => ({ typeOnlyReferences: 0, barrelExemptions: 0, generatedExemptions: 0, factoryExemptions: 0, deadBarrels: 0 });

test("class 1: type-only consumption counts as usage (opposite purpose from WO-9 layer law)", () => {
  const stats = newStats();
  const facts = [
    file("src/types.ts"),
    file("src/consumer.ts"),
    exp("src/types.ts", "Shape"),
    {
      kind: "import_specifier",
      subject: "src/consumer.ts:src/types.ts:Shape",
      value: { source: "src/consumer.ts", target: "./types", name: "Shape", local: "Shape", specifierKind: "named", typeOnly: true, resolvedTarget: "src/types.ts" },
    },
  ];
  const findings = policy.evaluateDeadCode({ facts, roots: [], stats });

  // The type-only edge references Shape: the file is alive.
  assert.deepEqual(findings, []);
  assert.equal(stats.typeOnlyReferences, 1);
});

test("class 2: barrel files are conduits - substantially-reexport files never flag, counted", () => {
  const stats = newStats();
  // WO-16 Part 2 scoped the exemption to LIVING conduits: the barrel
  // here carries a resolved importer.
  const facts = [
    file("src/barrel.ts"),
    file("src/orphanage.ts"),
    file("src/consumer.ts"),
    exp("src/barrel.ts", "a"),
    exp("src/barrel.ts", "b"),
    { kind: "reexport", subject: "src/barrel.ts:src/a.ts:a", value: { source: "src/barrel.ts", target: "./a", name: "a", exportedAs: "a", reexportKind: "named", resolvedTarget: "src/a.ts" } },
    { kind: "reexport", subject: "src/barrel.ts:src/b.ts:b", value: { source: "src/barrel.ts", target: "./b", name: "b", exportedAs: "b", reexportKind: "named", resolvedTarget: "src/b.ts" } },
    { kind: "import_specifier", subject: "src/consumer.ts:src/barrel.ts:a", value: { source: "src/consumer.ts", target: "./barrel", name: "a", local: "a", specifierKind: "named", resolvedTarget: "src/barrel.ts" } },
    // A genuinely dead file stays a finding.
    exp("src/orphanage.ts", "orphan"),
  ];
  const findings = policy.evaluateDeadCode({ facts, roots: [], stats });

  assert.deepEqual(findings.map((f) => f.files[0]), ["src/orphanage.ts"]);
  assert.equal(stats.barrelExemptions, 1);
});

test("class 3: generated files exempt by header signal or declared glob, counted", () => {
  // Header marker arrives as a provider content signal.
  const signals = jsts.extractContentSignalFacts(
    "core/config/gates.manifest.ts",
    "// AUTO-GENERATED FILE. DO NOT EDIT.\n// Generated by tools/build-gates.mjs\nexport const gates = [];\n",
  );

  assert.ok(signals.some((f) => f.value.signal === "generatedFile"));
  // The @generated convention itself also signals; deep-body mentions do not.
  assert.ok(jsts.extractContentSignalFacts("a.ts", "/** @generated */\n").some((f) => f.value.signal === "generatedFile"));
  assert.deepEqual(jsts.extractContentSignalFacts("a.ts", `${"const x = 1;\n".repeat(20)}// AUTO-GENERATED\n`), []);

  const stats = newStats();
  const facts = [
    file("core/config/gates.manifest.ts"),
    exp("core/config/gates.manifest.ts", "gates"),
    { kind: "content_signal", subject: "core/config/gates.manifest.ts", value: { signal: "generatedFile" } },
    file("scaffold/Shell.tsx"),
    exp("scaffold/Shell.tsx", "Shell"),
  ];

  // Marker exempts the manifest; the declared glob exempts the shell.
  const findings = policy.evaluateDeadCode({ facts, roots: [], generatedGlobs: ["scaffold/**"], stats });

  assert.deepEqual(findings, []);
  assert.equal(stats.generatedExemptions, 2);
});

test("declared public API annotations produce reachability evidence", () => {
  const facts = jsts.extractContentSignalFacts(
    "src/public.ts",
    "/** @publicApi */\nexport interface PublicContract {}\n",
  );
  assert.equal(facts.some((fact) => fact.kind === "content_signal" && fact.value.signal === "declaredPublicApi"), true);
});

test("class 4: factory exemption ONLY via the grammar's declared Factory role; unsuffixed stays residual", () => {
  const ratified = ontology.compileEffectiveGrammar({
    ratifiedArchetypeIds: ontology.BUILTIN_GRAMMAR_ARCHETYPE_PACKS.map((p) => p.id),
  });
  const stats = newStats();
  const facts = [
    file("core/services/VoiceServiceFactory.ts"),
    exp("core/services/VoiceServiceFactory.ts", "createVoiceServices"),
    file("infra/assemblies/main-assembly.ts"),
    exp("infra/assemblies/main-assembly.ts", "assemble"),
  ];
  const findings = policy.evaluateDeadCode({ facts, roots: [], grammar: ratified, stats });

  // The declared-role factory is exempt; the unsuffixed assembly file has
  // no deterministic signal - the finding STANDS (residual, never silent).
  assert.deepEqual(findings.map((f) => f.files[0]), ["infra/assemblies/main-assembly.ts"]);
  assert.equal(stats.factoryExemptions, 1);

  // Per-repo jurisdiction: without the grammar's declared role the
  // factory is not exempt.
  const bare = policy.evaluateDeadCode({ facts, roots: [] });
  assert.equal(bare.length, 2);
});

test("Part 2: operator-override topology compiles in and backs a firing evaluation", () => {
  const layer = (id, paths) => ({ id, name: id, description: "", position: 0, paths, source: "layers.ontology.yaml#layers.route" });
  const grammar = ontology.compileEffectiveGrammar({
    overrides: {
      layers: [layer("domain", ["domain/**"]), layer("instrumentation", ["infra/telemetry/**"])],
      topology: {
        archetype: "operator-overrides",
        description: "test constraint",
        requiredLayers: [],
        layerEdges: [{ fromLayer: "domain", toLayer: "instrumentation", required: false, forbidden: true }],
        source: "operator:wo-15#instrumentation-constraint",
      },
    },
  });

  assert.ok(grammar.topologies.get("operator-overrides"), "override topology joins the map");

  const findings = policy.evaluateGrammarDivergence({
    facts: [
      file("domain/engine.ts"),
      file("infra/telemetry/handoff.ts"),
      {
        kind: "import_specifier",
        subject: "domain/engine.ts:infra/telemetry/handoff.ts:mark",
        value: { source: "domain/engine.ts", target: "../infra", name: "mark", local: "mark", specifierKind: "named", resolvedTarget: "infra/telemetry/handoff.ts" },
      },
    ],
    grammar,
  });

  assert.equal(findings.length, 1);
  assert.equal(findings[0].payload.law.axis, "layer_import");
  assert.equal(findings[0].payload.law.packId, "operator-overrides");
  assert.match(findings[0].payload.law.declaration, /operator:wo-15#instrumentation-constraint/);
});

test("Part 2 regression: no-override compile carries no override topology; advisory topology never backs findings", () => {
  const grammar = ontology.compileEffectiveGrammar({});

  assert.equal(grammar.topologies.size, 0);

  // Advisory packs' topology may sit in the map for advisory evaluation,
  // but the detector's eligibility gate keeps findings at zero.
  const advisory = ontology.compileEffectiveGrammar({
    advisory: [ontology.BUILTIN_GRAMMAR_ARCHETYPE_PACKS[0].id],
  });
  const findings = policy.evaluateGrammarDivergence({
    facts: [
      file("app/api/x/route.ts"),
      file("core/domain/user.ts"),
      {
        kind: "import_specifier",
        subject: "app/api/x/route.ts:core/domain/user.ts:u",
        value: { source: "app/api/x/route.ts", target: "x", name: "u", local: "u", specifierKind: "named", resolvedTarget: "core/domain/user.ts" },
      },
    ],
    grammar: advisory,
  });

  assert.deepEqual(findings, [], "advisory topology stays advisory");
});
