// Base canon pack — common capability language across most repos.
//
// This pack is always included in the EffectiveCapabilityOntology.
// Overlay packs (nextjs-app, library-package, monorepo) and repo-
// local overrides extend or supersede it.
//
// Authoring rules:
// - Keep canonical entries conservative; only ship terms with broad
//   cross-repo applicability.
// - Aliases should map repo-specific phrasing onto the canonical
//   token (e.g. "make" -> "create", "persist" -> "save").
// - Noise tokens suppress suggestion noise (the normalizer still
//   records the raw evidence; only the review surface filters).

import { CANON_PACK_VERSION, type CapabilityOntologyPack } from "./types.js";

export const basePack: CapabilityOntologyPack = {
  id: "base",
  version: CANON_PACK_VERSION,
  description: "Common capability language across most repos.",
  isBase: true,
  verbs: {
    canonical: [
      { canonical: "get", category: "read", aliases: ["retrieve", "lookup", "read", "find"] },
      { canonical: "list", category: "read", aliases: ["all", "index", "enumerate"] },
      { canonical: "fetch", category: "read", aliases: ["query", "request"] },
      { canonical: "load", category: "read", aliases: ["pull"] },
      { canonical: "set", category: "write", aliases: ["assign", "store"] },
      { canonical: "save", category: "write", aliases: ["persist", "write"] },
      { canonical: "update", category: "write", aliases: ["modify", "patch", "edit", "change"] },
      { canonical: "create", category: "create", aliases: ["make", "add", "new"] },
      { canonical: "build", category: "create", aliases: ["construct", "compose", "assemble"] },
      { canonical: "delete", category: "delete", aliases: ["remove", "destroy", "drop"] },
      { canonical: "validate", category: "validate", aliases: ["ensure", "assert", "guard"] },
      { canonical: "verify", category: "validate", aliases: ["confirm"] },
      { canonical: "check", category: "validate", aliases: ["test"] },
      { canonical: "render", category: "transform", aliases: ["draw", "paint", "display"] },
      { canonical: "parse", category: "transform", aliases: ["decode", "interpret"] },
      { canonical: "format", category: "transform", aliases: ["serialize", "encode", "stringify"] },
      { canonical: "transform", category: "transform", aliases: ["convert", "map"] },
      { canonical: "normalize", category: "transform", aliases: [] },
      { canonical: "extract", category: "transform", aliases: ["pluck"] },
      { canonical: "generate", category: "transform", aliases: ["produce"] },
      { canonical: "resolve", category: "transform", aliases: [] },
      { canonical: "register", category: "system", aliases: ["enroll"] },
      { canonical: "handle", category: "system", aliases: ["process"] },
      { canonical: "execute", category: "system", aliases: ["run", "perform"] },
      { canonical: "route", category: "navigate", aliases: ["redirect"] },
      { canonical: "navigate", category: "navigate", aliases: ["goto"] },
      { canonical: "publish", category: "communicate", aliases: ["emit", "dispatch", "broadcast"] },
      { canonical: "subscribe", category: "communicate", aliases: ["listen", "watch"] },
      { canonical: "send", category: "communicate", aliases: ["post"] },
      { canonical: "receive", category: "communicate", aliases: ["consume"] },
      // Ported from legacy-source ontology (WO-4); per-key audit in verb-rules.ontology.yaml rows of
      // packages/capability-ontology/grammar-port-manifest.json.
      { canonical: "acces", category: "system", aliases: [] },
      { canonical: "cach", category: "system", aliases: [] },
      { canonical: "clear", category: "delete", aliases: [] },
      { canonical: "delegate", category: "system", aliases: [] },
      { canonical: "destroy", category: "delete", aliases: [] },
      { canonical: "initializ", category: "system", aliases: [] },
      { canonical: "log", category: "communicate", aliases: [] },
      { canonical: "schedule", category: "system", aliases: [] },
    ],
    // Ported from legacy-source verb-rules.ontology.yaml (WO-4):
    // 3rd-person capability-phrase forms reconciled onto base-form canon.
    aliases: {
      "accesses": "acces",
      "caches": "cach",
      "clears": "clear",
      "creates": "create",
      "delegates": "delegate",
      "destroys": "destroy",
      "handles": "handle",
      "initializes": "initializ",
      "loads": "load",
      "logs": "log",
      "schedules": "schedule",
      "updates": "update",
      "validates": "validate",
      "calls": "fetch",
      "collects": "fetch",
      "counts": "fetch",
      "finds": "fetch",
      "gets": "fetch",
      "ingests": "fetch",
      "queries": "fetch",
      "reads": "fetch",
      "retrieves": "fetch",
      "scans": "fetch",
      "searches": "fetch",
      "selects": "fetch",
      "lists": "fetch",
      "preloads": "load",
      "lazy-loads": "load",
      "imports": "load",
      "buffers": "cach",
      "remembers": "cach",
      "memoizes": "cach",
      "evicts": "clear",
      "invalidates": "clear",
      "asserts": "validate",
      "checks": "validate",
      "detects": "validate",
      "guards": "validate",
      "enforces": "validate",
      "monitors": "publish",
      "measures": "publish",
      "preserves": "validate",
      "prevents": "validate",
      "records": "publish",
      "respects": "validate",
      "tracks": "publish",
      "authenticates": "validate",
      "authorizes": "validate",
      "verifies": "validate",
      "adapts": "transform",
      "clones": "transform",
      "coerces": "transform",
      "converts": "transform",
      "decrypts": "transform",
      "deduplicates": "transform",
      "indexes": "transform",
      "decompresses": "extract",
      "enhances": "transform",
      "enriches": "transform",
      "encrypts": "transform",
      "filters": "transform",
      "aggregates": "transform",
      "groups": "transform",
      "hashes": "transform",
      "maps": "transform",
      "merges": "transform",
      "migrates": "transform",
      "normalizes": "transform",
      "ranks": "transform",
      "repairs": "transform",
      "fuses": "transform",
      "sorts": "transform",
      "applies": "transform",
      "appends": "update",
      "adds": "update",
      "attaches": "update",
      "deletes": "update",
      "disables": "update",
      "edits": "update",
      "inserts": "update",
      "mutates": "update",
      "refreshes": "update",
      "removes": "update",
      "revokes": "update",
      "syncs": "update",
      "synchronizes": "update",
      "sets": "update",
      "stores": "update",
      "adjusts": "update",
      "cancels": "update",
      "bootstraps": "initializ",
      "cleanups": "destroy",
      "closes": "destroy",
      "mounts": "initializ",
      "resets": "initializ",
      "restores": "load",
      "setups": "initializ",
      "starts": "initializ",
      "activates": "initializ",
      "stops": "destroy",
      "unmounts": "destroy",
      "expires": "clear",
      "prunes": "clear",
      "assembles": "build",
      "compiles": "build",
      "composes": "build",
      "constructs": "build",
      "expects": "build",
      "generates": "build",
      "synthesizes": "build",
      "mocks": "build",
      "spies": "build",
      "stubs": "build",
      "expands": "build",
      "redirects": "route",
      "distributes": "publish",
      "emits": "publish",
      "propagates": "publish",
      "alerts": "publish",
      "traces": "publish",
      "sends": "publish",
      "invokes": "delegate",
      "on": "handle",
      "off": "handle",
      "manages": "handle",
      "controls": "handle",
      "listens": "subscribe",
      "observes": "subscribe",
      "watches": "subscribe",
      "serializes": "format",
      "encodes": "format",
      "unwraps": "extract",
      "queues": "schedule",
      "debugs": "validate",
      "suppresses": "handle",
      "grounds": "validate",
      "organizes": "transform",
      "summarizes": "transform",
      "requests": "fetch",
      "picks": "fetch",
      "exports": "publish",
      "sanitizes": "validate",
      "should": "validate",
      "dispatches": "route",
    },
    noise: [
      "maybe", "todo", "fixme", "tbd",
      // Ported from classic verb-rules aliases judged auxiliary/unmappable (WO-4).
      "uses", "analyzes", "assesses", "categorizes", "compares", "can", "determines", "interprets", "scores", "infers", "resolves", "ensures", "has", "is", "matches", "prioritizes", "throttles", "debounces", "decodes", "estimates", "projects", "computes", "writes", "completes", "defines", "wires", "exposes", "extends", "implements", "wraps", "executes", "intercepts", "runs", "spawns", "deserializes", "coordinates", "finalizes", "fallbacks", "injects", "saves",
    ],
  },
  nouns: {
    canonical: [
      { canonical: "user", category: "domain", aliases: ["account", "person", "member"] },
      { canonical: "session", category: "domain", aliases: ["login"] },
      { canonical: "token", category: "infrastructure", aliases: ["secret", "credential", "apikey"] },
      { canonical: "config", category: "infrastructure", aliases: ["configuration", "settings", "options"] },
      { canonical: "file", category: "infrastructure", aliases: ["blob"] },
      { canonical: "route", category: "infrastructure", aliases: ["endpoint", "url", "path"] },
      { canonical: "handler", category: "infrastructure", aliases: [] },
      { canonical: "service", category: "infrastructure", aliases: ["manager"] },
      { canonical: "provider", category: "infrastructure", aliases: [] },
      { canonical: "report", category: "process", aliases: ["summary", "digest"] },
      { canonical: "artifact", category: "process", aliases: [] },
      { canonical: "finding", category: "process", aliases: [] },
      { canonical: "issue", category: "process", aliases: [] },
      { canonical: "plan", category: "process", aliases: [] },
      { canonical: "proof", category: "process", aliases: [] },
      { canonical: "command", category: "process", aliases: ["task"] },
      { canonical: "workflow", category: "process", aliases: ["pipeline"] },
      { canonical: "event", category: "process", aliases: [] },
      { canonical: "data", category: "data", aliases: [] },
      { canonical: "schema", category: "data", aliases: [] },
      { canonical: "state", category: "data", aliases: [] },
      { canonical: "result", category: "data", aliases: [] },
      { canonical: "context", category: "data", aliases: [] },
      { canonical: "memory", category: "data", aliases: [] },
      { canonical: "request", category: "infrastructure", aliases: ["req"] },
      { canonical: "response", category: "infrastructure", aliases: ["res", "reply"] },
      { canonical: "view", category: "ui", aliases: ["screen"] },
      { canonical: "form", category: "ui", aliases: [] },
      { canonical: "record", category: "data", aliases: ["row", "entity", "item", "doc", "document"] },
      // Ported from legacy-source ontology (WO-4); per-key audit in nouns.ontology.yaml rows of
      // packages/capability-ontology/grammar-port-manifest.json.
      { canonical: "analysis", category: "process", aliases: [] },
      { canonical: "assessment", category: "process", aliases: [] },
      { canonical: "cache", category: "infrastructure", aliases: [] },
      { canonical: "capability", category: "system", aliases: [] },
      { canonical: "conversation", category: "domain", aliases: [] },
      { canonical: "decision", category: "process", aliases: [] },
      { canonical: "embedding", category: "data", aliases: [] },
      { canonical: "experience", category: "domain", aliases: [] },
      { canonical: "export", category: "process", aliases: [] },
      { canonical: "feedback", category: "domain", aliases: [] },
      { canonical: "flow", category: "process", aliases: [] },
      { canonical: "gate", category: "process", aliases: [] },
      { canonical: "import", category: "process", aliases: [] },
      { canonical: "index", category: "data", aliases: [] },
      { canonical: "insight", category: "domain", aliases: [] },
      { canonical: "label", category: "data", aliases: [] },
      { canonical: "message", category: "domain", aliases: [] },
      { canonical: "module", category: "system", aliases: [] },
      { canonical: "ontology", category: "system", aliases: [] },
      { canonical: "persona", category: "domain", aliases: [] },
      { canonical: "preference", category: "domain", aliases: [] },
      { canonical: "profile", category: "domain", aliases: [] },
      { canonical: "progression", category: "domain", aliases: [] },
      { canonical: "prompt", category: "domain", aliases: [] },
      { canonical: "repository", category: "infrastructure", aliases: [] },
      { canonical: "router", category: "infrastructure", aliases: [] },
      { canonical: "stream", category: "process", aliases: [] },
      { canonical: "system", category: "system", aliases: [] },
      { canonical: "taxonomy", category: "system", aliases: [] },
      { canonical: "thread", category: "domain", aliases: [] },
    ],
    // Ported from legacy-source nouns.ontology.yaml (WO-4).
    aliases: {
      "cfg": "config",
      "cfgs": "config",
      "convo": "conversation",
      "msg": "message",
      "pref": "preference",
      "prefs": "preference",
      "repo": "repository",
      "repos": "repository",
      "svc": "service",
      "configuration": "config",
      "configurations": "config",
      "configuration object": "config",
      "configuration value": "config",
      "file path": "path",
      "file paths": "path",
      "path value": "path",
      "paths": "path",
      "token cost": "cost",
      "token costs": "cost",
      "llm response": "response",
      "response content": "response",
      "response output": "response",
      "intent plan markdown": "intent plan",
      "intent map": "intent plan",
      "failed gate kind": "gate kind",
      "gate type": "gate kind",
    },
    noise: ["thing", "stuff", "obj", "tmp"],
  },
  roles: {
    canonical: [
      { canonical: "controller" },
      { canonical: "service", aliases: ["manager"] },
      { canonical: "repository", aliases: ["repo", "store", "dao"] },
      { canonical: "view" },
      { canonical: "handler", aliases: ["listener"] },
    ],
    aliases: {},
  },
  patterns: {
    canonical: [
      { canonical: "crud" },
      { canonical: "rest-route", aliases: ["restful", "rest"] },
      { canonical: "background-job", aliases: ["worker", "queue"] },
      { canonical: "validator" },
    ],
    aliases: {},
  },
};
